
.TH "GCLOUD_SOURCE_REPOS_DELETE" 1



.SH "NAME"
.HP
gcloud source repos delete \- delete a cloud source repository



.SH "SYNOPSIS"
.HP
\f5gcloud source repos delete\fR \fIREPOSITORY_NAME\fR [\fB\-\-force\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command deletes a named git repository from the currently active Google
Cloud Platform project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIREPOSITORY_NAME\fR
Name of the repository.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-force\fR
If provided, skip the delete confirmation prompt.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To delete a named repository in the current project issue the following
commands:

.RS 2m
$ gcloud init
$ gcloud source repos delete REPOSITORY_NAME
.RE
