
.TH "GCLOUD_APP" 1



.SH "NAME"
.HP
gcloud app \- manage your App Engine deployments



.SH "SYNOPSIS"
.HP
\f5gcloud app\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

The gcloud app command group lets you deploy and manage your Google App Engine
apps. These commands replace their equivalents in the appcfg tool.

App Engine is a platform for building scalable web applications and mobile
backends. App Engine provides you with built\-in services and APIs such as NoSQL
datastores, memcache, and a user authentication API, common to most
applications.

More information on App Engine can be found here:
https://cloud.google.com/appengine and detailed documentation can be found here:
https://cloud.google.com/appengine/docs/



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBinstances\fR
View and manage your App Engine instances.

.TP 2m
\fBlogs\fR
Manage your App Engine logs.

.TP 2m
\fBoperations\fR
View and manage your App Engine Operations.

.TP 2m
\fBregions\fR
View regional availability of App Engine runtime environments.

.TP 2m
\fBservices\fR
View and manage your App Engine services.

.TP 2m
\fBversions\fR
View and manage your App Engine versions.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBbrowse\fR
Open the current app in a web browser.

.TP 2m
\fBcreate\fR
Create an App Engine app within the current Google Cloud Project.

.TP 2m
\fBdeploy\fR
Deploy the local code and/or configuration of your app to App Engine.

.TP 2m
\fBdescribe\fR
Display all data about an existing service.

.TP 2m
\fBopen\-console\fR
Open the App Engine dashboard, or log viewer, in a web browser.


.RE
.sp

.SH "EXAMPLES"

To run your app locally in the development application server, run:

.RS 2m
$ dev_appserver.py DEPLOYABLES
.RE

To create a new deployment of one or more services, run:

.RS 2m
$ gcloud app deploy DEPLOYABLES
.RE

To list your existing deployments, run:

.RS 2m
$ gcloud app versions list
.RE

To generate config files for your source directory:

.RS 2m
$ gcloud app gen\-config
.RE
