
.TH "GCLOUD_COMPUTE_NETWORKS_DELETE" 1



.SH "NAME"
.HP
gcloud compute networks delete \- delete Google Compute Engine networks



.SH "SYNOPSIS"
.HP
\f5gcloud compute networks delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute networks delete\fR deletes one or more Google Compute Engine
networks. Networks can only be deleted when no other resources (e.g., virtual
machine instances) refer to them.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The names of the networks to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
