
.TH "GCLOUD_APP_SERVICES" 1



.SH "NAME"
.HP
gcloud app services \- view and manage your App Engine services



.SH "SYNOPSIS"
.HP
\f5gcloud app services\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This set of commands can be used to view and manage your existing App Engine
services.

To create new deployments, use \f5gcloud app deploy\fR.

For more information on App Engine services, see:
https://cloud.google.com/appengine/docs/python/an\-overview\-of\-app\-engine



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBbrowse\fR
Open the specified service(s) in a browser.

.TP 2m
\fBdelete\fR
Delete services in the current project.

.TP 2m
\fBdescribe\fR
Display all data about an existing service.

.TP 2m
\fBlist\fR
List your existing services.

.TP 2m
\fBset\-traffic\fR
Set traffic splitting settings.


.RE
.sp

.SH "EXAMPLES"

To list your deployed services, run:

.RS 2m
$ gcloud app services list
.RE
