
.TH "GCLOUD_SPANNER_INSTANCES_REMOVE\-IAM\-POLICY\-BINDING" 1



.SH "NAME"
.HP
gcloud spanner instances remove\-iam\-policy\-binding \- remove an IAM policy binding from a Cloud Spanner instance



.SH "SYNOPSIS"
.HP
\f5gcloud spanner instances remove\-iam\-policy\-binding\fR \fIINSTANCE\fR \fB\-\-member\fR=\fIMEMBER\fR \fB\-\-role\fR=\fIROLE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Remove an IAM policy binding from a Cloud Spanner instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR
Cloud Spanner instance ID.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-member\fR=\fIMEMBER\fR
The member to add to the binding. Should be of the form \f5user:user_email\fR
(e.g. \f5user:test\-user@gmail.com.\fR)

.TP 2m
\fB\-\-role\fR=\fIROLE\fR
The role to remove the member from.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
