
.TH "GCLOUD_COMPUTE_NETWORKS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute networks describe \- describe a Google Compute Engine network



.SH "SYNOPSIS"
.HP
\f5gcloud compute networks describe\fR \fINAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute networks describe\fR displays all data associated with Google
Compute Engine network in a project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the network to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
