
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud iam service\-accounts set\-iam\-policy \- set IAM policy for a service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts set\-iam\-policy\fR \fIIAM_ACCOUNT\fR \fIPOLICY_FILE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command replaces the existing IAM policy for a service account, given an
IAM_ACCOUNT and a file encoded in JSON or YAML that contains the IAM policy. If
the given policy file specifies an "etag" value, then the replacement will
succeed only if the policy already in place matches that etag. (An etag obtained
via $ gcloud iam service\-accounts get\-iam\-policy will prevent the replacement
if the policy for the service account has been subsequently updated.) A policy
file that does not contain an etag value will replace any existing policy for
the service account.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIAM_ACCOUNT\fR
The service account whose policy to set.

.TP 2m
\fIPOLICY_FILE\fR
Path to a local JSON or YAML formatted file containing a valid policy.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

The following command will read an IAM policy defined in a JSON file
\'policy.json' and set it for a service account with identifier
\'my\-iam\-account@somedomain.com'

.RS 2m
$ gcloud iam service\-accounts set\-iam\-policy \e
    my\-iam\-account@somedomain.com policy.json
.RE


See https://cloud.google.com/iam/docs/managing\-policies for details of the
policy file format and contents.
