
.TH "GCLOUD_APP_VERSIONS" 1



.SH "NAME"
.HP
gcloud app versions \- view and manage your App Engine versions



.SH "SYNOPSIS"
.HP
\f5gcloud app versions\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This set of commands can be used to view and manage your existing App Engine
versions.

To create new deployments, use \f5gcloud app deploy\fR.

For more information on App Engine versions, see:
https://cloud.google.com/appengine/docs/python/an\-overview\-of\-app\-engine



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBbrowse\fR
Open the specified versions in a browser.

.TP 2m
\fBdelete\fR
Delete a specified version.

.TP 2m
\fBdescribe\fR
Display all data about an existing version.

.TP 2m
\fBlist\fR
List your existing versions.

.TP 2m
\fBmigrate\fR
Migrate traffic from one version to another for a set of services.

.TP 2m
\fBstart\fR
Start serving specified versions.

.TP 2m
\fBstop\fR
Stop serving specified versions.


.RE
.sp

.SH "EXAMPLES"

To list your deployed versions, run:

.RS 2m
$ gcloud app versions list
.RE
