
.TH "GCLOUD_COMPUTE_MACHINE\-TYPES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute machine\-types describe \- describe a Google Compute Engine machine type



.SH "SYNOPSIS"
.HP
\f5gcloud compute machine\-types describe\fR \fINAME\fR [\fB\-\-zone\fR=\fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute machine\-types describe\fR displays all data associated with a
Google Compute Engine machine type.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the machine type to describe.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-zone\fR=\fIZONE\fR
The zone of the machine type to describe. If not specified, you may be prompted
to select a zone.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/zone\fR\fR property:

.RS 2m
$ gcloud config set compute/zone ZONE
.RE

A list of zones can be fetched by running:

.RS 2m
$ gcloud compute zones list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/zone
.RE

Alternatively, the zone can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_ZONE\fR\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
