
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_KEYS_DELETE" 1



.SH "NAME"
.HP
gcloud iam service\-accounts keys delete \- delete a user\-managed key from a service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts keys delete\fR \fIKEY\-ID\fR \fB\-\-iam\-account\fR=\fIIAM_ACCOUNT\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete a user\-managed key from a service account.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIKEY\-ID\fR
The key to delete.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-iam\-account\fR=\fIIAM_ACCOUNT\fR
The service account whose key to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
