
.TH "GCLOUD_COMPUTE_URL\-MAPS_REMOVE\-PATH\-MATCHER" 1



.SH "NAME"
.HP
gcloud compute url\-maps remove\-path\-matcher \- remove a path matcher from a URL map



.SH "SYNOPSIS"
.HP
\f5gcloud compute url\-maps remove\-path\-matcher\fR \fIURL_MAP_NAME\fR \fB\-\-path\-matcher\-name\fR=\fIPATH_MATCHER_NAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute url\-maps remove\-path\-matcher\fR is used to remove a path
matcher from a URL map. When a path matcher is removed, all host rules that
refer to the path matcher are also removed.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIURL_MAP_NAME\fR
The name of the URL map to operate on.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-path\-matcher\-name\fR=\fIPATH_MATCHER_NAME\fR
The name of the path matcher to remove.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To remove the path matcher named \f5\fIMY\-MATCHER\fR\fR from the URL map named
\f5\fIMY\-URL\-MAP\fR\fR, you can use this command:

.RS 2m
$ gcloud compute url\-maps remove\-path\-matcher MY\-URL\-MAP \e
    \-\-path\-matcher MY\-MATCHER
.RE
