
.TH "GCLOUD_COMPONENTS_REMOVE" 1



.SH "NAME"
.HP
gcloud components remove \- remove one or more installed components



.SH "SYNOPSIS"
.HP
\f5gcloud components remove\fR \fICOMPONENT_ID\fR [\fICOMPONENT_ID\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Uninstall all listed components, as well as all components that directly or
indirectly depend on them.

The command lists all components it is about to remove, and asks for
confirmation before proceeding.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fICOMPONENT_ID\fR [\fICOMPONENT_ID\fR ...]
The IDs of the components to be removed.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To remove \f5\fICOMPONENT\-1\fR\fR, \f5\fICOMPONENT\-2\fR\fR, and all components
that directly or indirectly depend on \f5\fICOMPONENT\-1\fR\fR or
\f5\fICOMPONENT\-2\fR\fR, type the following:

.RS 2m
$ gcloud components remove COMPONENT\-1 COMPONENT\-2
.RE
