
.TH "GCLOUD_CONTAINER_IMAGES_UNTAG" 1



.SH "NAME"
.HP
gcloud container images untag \- remove existing image tags



.SH "SYNOPSIS"
.HP
\f5gcloud container images untag\fR \fIIMAGE_NAME\fR [\fIIMAGE_NAME\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

The container images untag command removes the specified tag from the image.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIMAGE_NAME\fR [\fIIMAGE_NAME\fR ...]
The IMAGE_NAME(S) to untag

Format: \f5*.gcr.io/repository:<tag>\fR


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

Removes the tag from the input IMAGE_NAME:

.RS 2m
$ gcloud container images untag <IMAGE_NAME>
.RE
