
.TH "GCLOUD_FIREBASE_TEST" 1



.SH "NAME"
.HP
gcloud firebase test \- interact with Firebase Test Lab



.SH "SYNOPSIS"
.HP
\f5gcloud firebase test\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Explore devices and OS versions available as test targets, run tests, monitor
test progress, and view detailed test results in the Firebase console.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBandroid\fR
Command group for Android application testing.
.RE
.sp
