
.TH "GCLOUD_COMPUTE_TARGET\-SSL\-PROXIES_UPDATE" 1



.SH "NAME"
.HP
gcloud compute target\-ssl\-proxies update \- update a target SSL proxy



.SH "SYNOPSIS"
.HP
\f5gcloud compute target\-ssl\-proxies update\fR \fINAME\fR [\fB\-\-backend\-service\fR=\fIBACKEND_SERVICE\fR] [\fB\-\-proxy\-header\fR=\fIPROXY_HEADER\fR] [\fB\-\-ssl\-certificate\fR=\fISSL_CERTIFICATE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute target\-ssl\-proxies update\fR is used to change the SSL
certificate, backend service or proxy header of existing target SSL proxies. A
target SSL proxy is referenced by one or more forwarding rules which define
which packets the proxy is responsible for routing. The target SSL proxy in turn
points to a backend service which will handle the requests. The target SSL proxy
also points to an SSL certificate used for server\-side authentication.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the target SSL proxy to update.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-backend\-service\fR=\fIBACKEND_SERVICE\fR
A backend service that will be used for connections to the target SSL proxy.

.TP 2m
\fB\-\-proxy\-header\fR=\fIPROXY_HEADER\fR
The type of proxy protocol header to be sent to the backend. \fIPROXY_HEADER\fR
must be one of:

.RS 2m
.TP 2m
\fBNONE\fR
No proxy header is added.
.TP 2m
\fBPROXY_V1\fR
Enables PROXY protocol (version 1) for passing client connection information.

.RE
.sp
.TP 2m
\fB\-\-ssl\-certificate\fR=\fISSL_CERTIFICATE\fR
A reference to an SSL certificate resource that is used for server\-side
authentication. The SSL certificate must exist and cannot be deleted while
referenced by a target SSL proxy.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
