
.TH "GCLOUD_DATAFLOW_JOBS_DRAIN" 1



.SH "NAME"
.HP
gcloud dataflow jobs drain \- drains all jobs that match the command line arguments



.SH "SYNOPSIS"
.HP
\f5gcloud dataflow jobs drain\fR \fIJOB_ID\fR [\fIJOB_ID\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Once Drain is triggered, the pipeline will stop accepting new inputs. The input
watermark will be advanced to infinity. Elements already in the pipeline will
continue to be processed. Drained jobs can safely be cancelled.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB_ID\fR [\fIJOB_ID\fR ...]
The job IDs to operate on.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
