
.TH "GCLOUD_COMPUTE_FIREWALL\-RULES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute firewall\-rules describe \- describe a Google Compute Engine firewall rule



.SH "SYNOPSIS"
.HP
\f5gcloud compute firewall\-rules describe\fR \fINAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute firewall\-rules describe\fR displays all data associated with
a Google Compute Engine firewall rule in a project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the firewall rule to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
