
.TH "GCLOUD_SQL_DATABASES" 1



.SH "NAME"
.HP
gcloud sql databases \- provide commands for managing databases of Cloud SQL instances



.SH "SYNOPSIS"
.HP
\f5gcloud sql databases\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Provide commands for managing databases of Cloud SQL instances, including
creating, deleting, listing, patching, updating, and getting information about
databases.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Creates a database for a Cloud SQL instance.

.TP 2m
\fBdelete\fR
Deletes a Cloud SQL database.

.TP 2m
\fBdescribe\fR
Displays configuration and metadata about a Cloud SQL database.

.TP 2m
\fBlist\fR
Lists databases for a Cloud SQL instance.

.TP 2m
\fBpatch\fR
Patches the settings of a Cloud SQL database.
.RE
.sp
