
.TH "GCLOUD_COMPUTE_HEALTH\-CHECKS_DELETE" 1



.SH "NAME"
.HP
gcloud compute health\-checks delete \- delete health checks



.SH "SYNOPSIS"
.HP
\f5gcloud compute health\-checks delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute health\-checks delete\fR deletes one or more Google Compute
Engine health checks.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The names of the health checks to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
