
.TH "GCLOUD_SPANNER_OPERATIONS" 1



.SH "NAME"
.HP
gcloud spanner operations \- manage Cloud Spanner operations



.SH "SYNOPSIS"
.HP
\f5gcloud spanner operations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud Spanner operations.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcancel\fR
Cancel a Cloud Spanner operation.

.TP 2m
\fBdescribe\fR
Describe a Cloud Spanner operation.

.TP 2m
\fBlist\fR
List the Cloud Spanner operations on the given instance or database.
.RE
.sp
