
.TH "GCLOUD_CONFIG_CONFIGURATIONS_DELETE" 1



.SH "NAME"
.HP
gcloud config configurations delete \- deletes a named configuration



.SH "SYNOPSIS"
.HP
\f5gcloud config configurations delete\fR \fICONFIGURATION_NAMES\fR [\fICONFIGURATION_NAMES\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Deletes a named configuration. You cannot delete a configuration that is active,
even when overridden with the \-\-configuration flag. To delete the current
active configuration, first \f5gcloud config configurations activate\fR another
one.

See \f5gcloud topic configurations\fR for an overview of named configurations.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fICONFIGURATION_NAMES\fR [\fICONFIGURATION_NAMES\fR ...]
Name of the configuration to delete. Cannot be currently active configuration.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To delete a named configuration, run:

.RS 2m
$ gcloud config configurations delete my_config
.RE

To delete more than one configuration, run:

.RS 2m
$ gcloud config configurations delete my_config1 my_config2
.RE

To list existing configurations, run:

.RS 2m
$ gcloud config configurations list
.RE
