
.TH "GCLOUD_AUTH_APPLICATION\-DEFAULT_PRINT\-ACCESS\-TOKEN" 1



.SH "NAME"
.HP
gcloud auth application\-default print\-access\-token \- print an access token for the your current Application Default Credentials



.SH "SYNOPSIS"
.HP
\f5gcloud auth application\-default print\-access\-token\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Once you have generated Application Default Credentials using \f5gcloud auth
application\-default login\fR, you can use this command to generate and print an
access token that can be directly used for making an API call. This can be
useful for manually testing out APIs via curl.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
