
.TH "GCLOUD_SERVICE\-MANAGEMENT_ENABLE" 1



.SH "NAME"
.HP
gcloud service\-management enable \- enables a service for consumption for a project



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management enable\fR \fISERVICE\fR [\fB\-\-async\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command enables a service for consumption for a project.

To see a list of available services for a project, run:

.RS 2m
$ gcloud service\-management list \-\-available
.RE

More information on listing services can be found at:
https://cloud.google.com/service\-management/list\-services and on enabling a
service at:
https://cloud.google.com/service\-management/enable\-disable#enabling_services



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISERVICE\fR
The name of the service to enable.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress, without waiting for the
operation to complete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To enable a service called \f5my\-consumed\-service\fR on the current project,
run:

.RS 2m
$ gcloud service\-management enable my\-consumed\-service
.RE

To run the same command asynchronously (non\-blocking), run:

.RS 2m
$ gcloud service\-management enable my\-consumed\-service \-\-async
.RE
