
.TH "GCLOUD_CONTAINER_NODE\-POOLS_ROLLBACK" 1



.SH "NAME"
.HP
gcloud container node\-pools rollback \- rollback a node\-pool upgrade



.SH "SYNOPSIS"
.HP
\f5gcloud container node\-pools rollback\fR \fINAME\fR [\fB\-\-async\fR] [\fB\-\-cluster\fR=\fICLUSTER\fR] [\fB\-\-zone\fR=\fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Rollback a node\-pool upgrade.

Rollback is a method used after a canceled or failed node\-pool upgrade. It
makes a best\-effort attempt to revert the pool back to its original state.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the node pool to rollback.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Don't wait for the operation to complete.

.TP 2m
\fB\-\-cluster\fR=\fICLUSTER\fR
The cluster from which to rollback the node pool. Overrides the default
\fBcontainer/cluster\fR property value for this command invocation.

.TP 2m
\fB\-\-zone\fR=\fIZONE\fR, \fB\-z\fR \fIZONE\fR
The compute zone (e.g. us\-central1\-a) for the cluster. Overrides the default
\fBcompute/zone\fR property value for this command invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
