
.TH "GCLOUD_APP_SERVICES_DELETE" 1



.SH "NAME"
.HP
gcloud app services delete \- delete services in the current project



.SH "SYNOPSIS"
.HP
\f5gcloud app services delete\fR \fISERVICES\fR [\fISERVICES\fR\ ...] [\fB\-\-version\fR=\fIVERSION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete services in the current project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISERVICES\fR [\fISERVICES\fR ...]
The service(s) to delete.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-version\fR=\fIVERSION\fR
Delete a specific version of the given service(s).


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To delete a service (and all of its accompanying versions) in the current
project, run:

.RS 2m
$ gcloud app services delete service1
.RE

To delete multiple services (and all of their accompanying versions) in the
current project, run:

.RS 2m
$ gcloud app services delete service1 service2
.RE
