
.TH "GCLOUD_APP_VERSIONS_START" 1



.SH "NAME"
.HP
gcloud app versions start \- start serving specified versions



.SH "SYNOPSIS"
.HP
\f5gcloud app versions start\fR \fIVERSIONS\fR [\fIVERSIONS\fR\ ...] [\fB\-\-service\fR=\fISERVICE\fR,\ \fB\-s\fR\ \fISERVICE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command starts serving the specified versions. It may only be used if the
scaling module for your service has been set to manual.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIVERSIONS\fR [\fIVERSIONS\fR ...]
The versions to start. (optionally filtered by the \-\-service flag).


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-service\fR=\fISERVICE\fR, \fB\-s\fR \fISERVICE\fR
If specified, only start versions from the given service.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To start a specific version across all services, run:

.RS 2m
$ gcloud app versions start v1
.RE

To start multiple named versions across all services, run:

.RS 2m
$ gcloud app versions start v1 v2
.RE

To start a single version on a single service, run:

.RS 2m
$ gcloud app versions start \-\-service servicename v1
.RE

To start multiple versions in a single service, run:

.RS 2m
$ gcloud app versions start \-\-service servicename v1 v2
.RE
