
.TH "GCLOUD_COMPUTE_PROJECT\-INFO_REMOVE\-METADATA" 1



.SH "NAME"
.HP
gcloud compute project\-info remove\-metadata \- remove project\-wide metadata entries



.SH "SYNOPSIS"
.HP
\f5gcloud compute project\-info remove\-metadata\fR [\fB\-\-all\fR\ |\ \fB\-\-keys\fR=\fIKEY\fR,[\fIKEY\fR,...]] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute project\-info remove\-metadata\fR can be used to remove
project\-wide metadata entries.



.SH "FLAGS"

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-all\fR
If provided, all metadata entries are removed.

.TP 2m
\fB\-\-keys\fR=\fIKEY\fR,[\fIKEY\fR,...]
The keys of the entries to remove.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
