
.TH "GCLOUD_COMPUTE_REGIONS" 1



.SH "NAME"
.HP
gcloud compute regions \- list Google Compute Engine regions



.SH "SYNOPSIS"
.HP
\f5gcloud compute regions\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

List Google Compute Engine regions.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Describe a Google Compute Engine region.

.TP 2m
\fBlist\fR
List Google Compute Engine regions.
.RE
.sp
