
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud iam service\-accounts describe \- show metadata for a service account from a project



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts describe\fR \fIIAM_ACCOUNT\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command shows metadata for a service account.

This call can fail for the following reasons:
.RS 2m
.IP "\(bu" 2m
The service account specified does not exist.
.IP "\(bu" 2m
The active user does not have permission to access the given service account.
.RE
.sp



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIAM_ACCOUNT\fR
The service account to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To print metadata for a service account from your project, run:

.RS 2m
$ gcloud iam service\-accounts describe my\-iam\-account@somedomain.com
.RE
