
.TH "GCLOUD_DNS_PROJECT\-INFO" 1



.SH "NAME"
.HP
gcloud dns project\-info \- view Cloud DNS related information for a project



.SH "SYNOPSIS"
.HP
\f5gcloud dns project\-info\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

View Cloud DNS related information for a project.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
View Cloud DNS related information for a project.


.RE
.sp

.SH "EXAMPLES"

To display Cloud DNS related information for your project, run:

.RS 2m
$ gcloud dns project\-info describe
.RE
