
.TH "GCLOUD_DATASTORE" 1



.SH "NAME"
.HP
gcloud datastore \- manage your Cloud Datastore indexes



.SH "SYNOPSIS"
.HP
\f5gcloud datastore\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

The gcloud datastore command group lets you create and delete Google Cloud
Datastore indexes.

Cloud Datastore is a highly\-scalable NoSQL database for your applications.
Cloud Datastore automatically handles sharding and replication, providing you
with a highly available and durable database that scales automatically to handle
your applications' load.

More information on Cloud Datastore can be found here:
https://cloud.google.com/datastore and detailed documentation can be found here:
https://cloud.google.com/datastore/docs



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcleanup\-indexes\fR
Remove unused datastore indexes based on your local index configuration.

.TP 2m
\fBcreate\-indexes\fR
Create new datastore indexes based on your local index configuration.


.RE
.sp

.SH "EXAMPLES"

To create new indexes from a file, run:

.RS 2m
$ gcloud datastore create\-indexes index.yaml
.RE

To clean up unused indexes from a file, run:

.RS 2m
$ gcloud datastore cleanup\-indexes index.yaml
.RE
