
.TH "GCLOUD_COMPUTE_ACCELERATOR\-TYPES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute accelerator\-types describe \- describe Google Compute Engine accelerator types



.SH "SYNOPSIS"
.HP
\f5gcloud compute accelerator\-types describe\fR \fINAME\fR [\fB\-\-zone\fR=\fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute accelerator\-types describe\fR displays all data associated
with a Google Compute Engine accelerator type.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the accelerator type to describe.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-zone\fR=\fIZONE\fR
The zone of the accelerator type to describe. Overrides the default
\fBcompute/zone\fR property value for this command invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
