
.TH "GCLOUD_DNS_RECORD\-SETS_TRANSACTION_DESCRIBE" 1



.SH "NAME"
.HP
gcloud dns record\-sets transaction describe \- describe the transaction



.SH "SYNOPSIS"
.HP
\f5gcloud dns record\-sets transaction describe\fR \fB\-\-zone\fR=\fIZONE\fR, \fB\-z\fR \fIZONE\fR [\fB\-\-transaction\-file\fR=\fITRANSACTION_FILE\fR;\ default="transaction.yaml"] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command displays the contents of the transaction.



.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-zone\fR=\fIZONE\fR, \fB\-z\fR \fIZONE\fR
Name of the managed\-zone whose record\-sets you want to manage.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-transaction\-file\fR=\fITRANSACTION_FILE\fR; default="transaction.yaml"
Path of the file which contains the transaction.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To look at the contents of the transaction, run:

.RS 2m
$ gcloud dns record\-sets transaction describe \-\-zone MANAGED_ZONE
.RE
