
.TH "GCLOUD_APP_CREATE" 1



.SH "NAME"
.HP
gcloud app create \- create an App Engine app within the current Google Cloud Project



.SH "SYNOPSIS"
.HP
\f5gcloud app create\fR [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Create an App Engine app within the current Google Cloud Project.



.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region to create the app within. Use \f5gcloud app regions list\fR to list
available regions. If not provided, select region interactively.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To create an app with region chosen interactively, run:

.RS 2m
$ gcloud app create
.RE

To create an app in the us\-central region, run:

.RS 2m
$ gcloud app create \-\-region=us\-central
.RE
