
.TH "GCLOUD_COMPUTE_IMAGES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute images describe \- describe a Google Compute Engine image



.SH "SYNOPSIS"
.HP
\f5gcloud compute images describe\fR \fIIMAGE_NAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute images describe\fR displays all data associated with a Google
Compute Engine image in a project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIMAGE_NAME\fR
The name of the disk image to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
