
.TH "GCLOUD_SPANNER_INSTANCES_GET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud spanner instances get\-iam\-policy \- get the IAM policy for a Cloud Spanner instance



.SH "SYNOPSIS"
.HP
\f5gcloud spanner instances get\-iam\-policy\fR \fIINSTANCE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Get the IAM policy for a Cloud Spanner instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR
Cloud Spanner instance ID.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
