
.TH "GCLOUD_APP_LOGS" 1



.SH "NAME"
.HP
gcloud app logs \- manage your App Engine logs



.SH "SYNOPSIS"
.HP
\f5gcloud app logs\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This set of commands can be used to view your existing App Engine logs.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBread\fR
Reads log entries for the current App Engine app.

.TP 2m
\fBtail\fR
Streams logs for App Engine apps.


.RE
.sp

.SH "EXAMPLES"

To read the logs for the current App Engine project, run:

.RS 2m
$ gcloud app logs read
.RE
