
.TH "GCLOUD_COMPUTE_XPN_ORGANIZATIONS" 1



.SH "NAME"
.HP
gcloud compute xpn organizations \- configure organizations for cross\-project networking (XPN)



.SH "SYNOPSIS"
.HP
\f5gcloud compute xpn organizations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Configure organizations for cross\-project networking (XPN).



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlist\-host\-projects\fR
List projects in a given organization that are enabled as XPN hosts.
.RE
.sp
