
.TH "GCLOUD_CONTAINER_BUILDS_LOG" 1



.SH "NAME"
.HP
gcloud container builds log \- stream the logs for a build



.SH "SYNOPSIS"
.HP
\f5gcloud container builds log\fR \fIBUILD\fR [\fB\-\-stream\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Stream the logs for a build.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIBUILD\fR
The build whose logs shall be printed. The ID of the build is printed at the end
of the build submission process, or in the ID column when listing builds.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-stream\fR
If a build is ongoing, stream the logs to stdout until termination.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
