
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_SIGN\-BLOB" 1



.SH "NAME"
.HP
gcloud iam service\-accounts sign\-blob \- sign a blob with a managed service account key



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts sign\-blob\fR \fIINPUT\-FILE\fR \fIOUTPUT\-FILE\fR \fB\-\-iam\-account\fR=\fIIAM_ACCOUNT\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command signs a file containing arbitrary binary data (a blob) using a
system\-managed service account key.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINPUT\-FILE\fR
A path to the blob file to be signed.

.TP 2m
\fIOUTPUT\-FILE\fR
A path the resulting signed blob will be written to.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-iam\-account\fR=\fIIAM_ACCOUNT\fR
The service account to sign as.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To sign a blob file with a system\-managed service account key, run:

.RS 2m
$ gcloud iam service\-accounts sign\-blob \e
    \-\-iam\-account my\-account@somedomain.com input.bin output.bin
.RE



.SH "SEE ALSO"

For more information on how this command ties into the wider cloud
infrastructure, please see
https://cloud.google.com/appengine/docs/java/appidentity/
