
.TH "GCLOUD_CONTAINER_BUILDS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud container builds describe \- get information about a particular build



.SH "SYNOPSIS"
.HP
\f5gcloud container builds describe\fR \fIBUILD\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Get information about a particular build.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIBUILD\fR
The build to describe. The ID of the build is printed at the end of the build
submission process, or in the ID column when listing builds.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
