
.TH "GCLOUD_CONTAINER_CLUSTERS_DELETE" 1



.SH "NAME"
.HP
gcloud container clusters delete \- delete an existing cluster for running containers



.SH "SYNOPSIS"
.HP
\f5gcloud container clusters delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fB\-\-async\fR] [\fB\-\-zone\fR=\fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete an existing cluster for running containers.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The names of the clusters to delete.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Don't wait for the operation to complete.

.TP 2m
\fB\-\-zone\fR=\fIZONE\fR, \fB\-z\fR \fIZONE\fR
The compute zone (e.g. us\-central1\-a) for the cluster. Overrides the default
\fBcompute/zone\fR property value for this command invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
