
.TH "GCLOUD_KMS_KEYS_VERSIONS_CREATE" 1



.SH "NAME"
.HP
gcloud kms keys versions create \- create a new version



.SH "SYNOPSIS"
.HP
\f5gcloud kms keys versions create\fR [\fB\-\-key\fR=\fIKEY\fR] [\fB\-\-keyring\fR=\fIKEYRING\fR] [\fB\-\-location\fR=\fILOCATION\fR] [\fB\-\-primary\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Creates a new version within the given key.



.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-key\fR=\fIKEY\fR
The containing key.

.TP 2m
\fB\-\-keyring\fR=\fIKEYRING\fR
The containing keyring.

.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
The location of the requested resource.

.TP 2m
\fB\-\-primary\fR
If specified, immediately make the new version primary.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

The following command creates a new version within the \f5frodo\fR key,
\f5fellowship\fR keyring, and \f5global\fR location and sets it as the primary
version:

.RS 2m
$ gcloud kms keys versions create \-\-location global \e
    \-\-keyring fellowship \e
    \-\-key frodo \-\-primary
.RE
