
.TH "GCLOUD_ML\-ENGINE_JOBS_SUBMIT" 1



.SH "NAME"
.HP
gcloud ml\-engine jobs submit \- cloud ML Engine Jobs submit commands



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine jobs submit\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Cloud ML Engine Jobs submit commands.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBprediction\fR
Start a Cloud ML Engine batch prediction job.

.TP 2m
\fBtraining\fR
Submits a Cloud Machine Learning training job.
.RE
.sp
