
.TH "GCLOUD_SQL_INSTANCES_RESTORE\-BACKUP" 1



.SH "NAME"
.HP
gcloud sql instances restore\-backup \- restores a backup of a Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql instances restore\-backup\fR \fIINSTANCE\fR (\fB\-\-backup\-id\fR=\fIBACKUP_ID\fR\ |\ \fB\-\-due\-time\fR=\fIDUE_TIME\fR) [\fB\-\-async\fR] [\fB\-\-backup\-instance\fR=\fIBACKUP_INSTANCE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

DEPRECATED: This command is deprecated and will be removed. Use 'gcloud beta sql
backups restore' instead.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR
Cloud SQL instance ID that will be restored.


.RE
.sp

.SH "REQUIRED FLAGS"

Exactly one of these must be specified:

.RS 2m
.TP 2m
\fB\-\-backup\-id\fR=\fIBACKUP_ID\fR
The ID of the backup run to restore from.

.TP 2m
\fB\-\-due\-time\fR=\fIDUE_TIME\fR
The time when this run was due to start in RFC 3339 format, for example
2012\-11\-15T16:19:00.094Z.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Do not wait for the operation to complete.

.TP 2m
\fB\-\-backup\-instance\fR=\fIBACKUP_INSTANCE\fR
The ID of the instance that the backup was taken from.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
