
.TH "GCLOUD_COMPUTE_ZONES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute zones describe \- describe a Google Compute Engine zone



.SH "SYNOPSIS"
.HP
\f5gcloud compute zones describe\fR \fINAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute zones describe\fR displays all data associated with a Google
Compute Engine zone.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the zone to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
