
.TH "GCLOUD_SOURCE" 1



.SH "NAME"
.HP
gcloud source \- cloud git repository commands



.SH "SYNOPSIS"
.HP
\f5gcloud source\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

The gcloud source group lets you manipulate git repositories within a Google
Cloud project.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBrepos\fR
Manage cloud source repositories.
.RE
.sp
