
.TH "GCLOUD_DNS_MANAGED\-ZONES_CREATE" 1



.SH "NAME"
.HP
gcloud dns managed\-zones create \- create a Cloud DNS managed\-zone



.SH "SYNOPSIS"
.HP
\f5gcloud dns managed\-zones create\fR \fIZONE_NAME\fR \fB\-\-description\fR=\fIDESCRIPTION\fR \fB\-\-dns\-name\fR=\fIDNS_NAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command creates a Cloud DNS managed\-zone.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIZONE_NAME\fR
The name of the managed\-zone to be created.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-description\fR=\fIDESCRIPTION\fR
Short description for the managed\-zone.

.TP 2m
\fB\-\-dns\-name\fR=\fIDNS_NAME\fR
The DNS name suffix that will be managed with the created zone.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To create a managed\-zone, run:

.RS 2m
$ gcloud dns managed\-zones create my_zone \-\-dns\-name my.zone.com. \e
    \-\-description "My zone!"
.RE
