
.TH "GCLOUD_DATAFLOW_JOBS_RUN" 1



.SH "NAME"
.HP
gcloud dataflow jobs run \- runs a job from the specified path



.SH "SYNOPSIS"
.HP
\f5gcloud dataflow jobs run\fR \fIJOB_NAME\fR \fB\-\-gcs\-location\fR=\fIGCS_LOCATION\fR [\fB\-\-max\-workers\fR=\fIMAX_WORKERS\fR] [\fB\-\-parameters\fR=[\fIPARAMETERS\fR,...]] [\fB\-\-service\-account\-email\fR=\fISERVICE_ACCOUNT_EMAIL\fR] [\fB\-\-zone\fR=\fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Runs a job from the specified path.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB_NAME\fR
The unique name to assign to the job.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-gcs\-location\fR=\fIGCS_LOCATION\fR
The location of the job template to run.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-max\-workers\fR=\fIMAX_WORKERS\fR
The maximum number of workers to run.

.TP 2m
\fB\-\-parameters\fR=[\fIPARAMETERS\fR,...]
The parameters to pass to the job.

.TP 2m
\fB\-\-service\-account\-email\fR=\fISERVICE_ACCOUNT_EMAIL\fR
The service account to run the workers as.

.TP 2m
\fB\-\-zone\fR=\fIZONE\fR
The zone to run the workers in.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
