
.TH "GCLOUD_COMPUTE_ROUTERS" 1



.SH "NAME"
.HP
gcloud compute routers \- list, create, and delete Google Compute Engine routers



.SH "SYNOPSIS"
.HP
\f5gcloud compute routers\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

List, create, and delete Google Compute Engine routers.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-bgp\-peer\fR
Add a BGP peer to a Google Compute Engine router.

.TP 2m
\fBadd\-interface\fR
Add an interface to a Google Compute Engine router.

.TP 2m
\fBcreate\fR
Create a Google Compute Engine router.

.TP 2m
\fBdelete\fR
Delete Google Compute Engine routers.

.TP 2m
\fBdescribe\fR
Describe a Google Compute Engine router.

.TP 2m
\fBget\-status\fR
Get status of a Google Compute Engine router.

.TP 2m
\fBlist\fR
List Google Compute Engine routers.

.TP 2m
\fBremove\-bgp\-peer\fR
Remove a BGP peer from a Google Compute Engine router.

.TP 2m
\fBremove\-interface\fR
Remove an interface from a Google Compute Engine router.

.TP 2m
\fBupdate\-bgp\-peer\fR
Update a BGP peer on a Google Compute Engine router.

.TP 2m
\fBupdate\-interface\fR
Update an interface on a Google Compute Engine router.
.RE
.sp
