
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_GET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud iam service\-accounts get\-iam\-policy \- get the IAM policy for a service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts get\-iam\-policy\fR \fIIAM_ACCOUNT\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command gets the IAM policy for a service account. If formatted as JSON,
the output can be edited and used as a policy file for set\-iam\-policy. The
output includes an "etag" field identifying the version emitted and allowing
detection of concurrent policy updates; see $ gcloud iam service\-accounts
set\-iam\-policy for additional details.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIAM_ACCOUNT\fR
The service account whose policy to get.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To print the IAM policy for a given service account, run:

.RS 2m
$ gcloud iam service\-accounts get\-iam\-policy \e
    my\-iam\-account@somedomain.com
.RE
