
.TH "GCLOUD_APP_VERSIONS_DELETE" 1



.SH "NAME"
.HP
gcloud app versions delete \- delete a specified version



.SH "SYNOPSIS"
.HP
\f5gcloud app versions delete\fR \fIVERSIONS\fR [\fIVERSIONS\fR\ ...] [\fB\-\-service\fR=\fISERVICE\fR,\ \fB\-s\fR\ \fISERVICE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

You cannot delete a version of a service that is currently receiving traffic.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIVERSIONS\fR [\fIVERSIONS\fR ...]
The versions to delete (optionally filtered by the \-\-service flag).


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-service\fR=\fISERVICE\fR, \fB\-s\fR \fISERVICE\fR
If specified, only delete versions from the given service.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To delete a specific version of a specific service, run:

.RS 2m
$ gcloud app versions delete \-\-service myService v1
.RE

To delete a named version across all services, run:

.RS 2m
$ gcloud app versions delete v1
.RE

To delete multiple versions of a specific service, run:

.RS 2m
$ gcloud app versions delete \-\-service myService v1 v2
.RE

To delete multiple named versions across all services, run:

.RS 2m
$ gcloud app versions delete v1 v2
.RE
