
.TH "GCLOUD_SERVICE\-MANAGEMENT_UNDELETE" 1



.SH "NAME"
.HP
gcloud service\-management undelete \- undeletes a service given a service name



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management undelete\fR \fISERVICE\fR [\fB\-\-async\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Undeletes a service configuration that was previously deleted.

Services that are deleted will be retained in the system for 30 days. If a
deleted service is still within this retention window, it can be undeleted with
this command.

Note that this means that this command will not be effective for service
configurations marked for deletion more than 30 days ago.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISERVICE\fR
The name of the service to undelete.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress, without waiting for the
operation to complete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To undelete a service named \f5my\-service\fR, run:

.RS 2m
$ gcloud service\-management undelete my\-service
.RE

To run the same command asynchronously (non\-blocking), run:

.RS 2m
$ gcloud service\-management undelete my\-service \-\-async
.RE
