
.TH "GCLOUD_DATAPROC_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud dataproc operations describe \- view the details of an operation



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc operations describe\fR \fIOPERATION\fR [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

View the details of an operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR
The ID of the operation to describe.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Specifies the Cloud Dataproc region to use. Each Cloud Dataproc region
constitutes an independent resource namespace constrained to deploying instances
into Google Compute Engine zones inside the region. The default value of
"global" is a special multi\-region namespace which is capable of deploying
instances into all Google Compute Engine zones globally, and is disjoint from
other Cloud Dataproc regions. Overrides the default \fBdataproc/region\fR
property value for this command invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To view the details of an operation, run:

.RS 2m
$ gcloud dataproc operations describe operation_id
.RE
