
.TH "GCLOUD_FIREBASE_TEST_ANDROID_MODELS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud firebase test android models describe \- describe an Android model



.SH "SYNOPSIS"
.HP
\f5gcloud firebase test android models describe\fR \fIMODEL_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Describe an Android model.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIMODEL_ID\fR
ID of the model to describe, found using $ gcloud firebase test android models
list.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
