
.TH "GCLOUD_SQL_BACKUPS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud sql backups describe \- retrieves information about a backup



.SH "SYNOPSIS"
.HP
\f5gcloud sql backups describe\fR \fIID\fR \fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Retrieves information about a backup.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIID\fR
The ID of the Backup Run.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
