
.TH "GCLOUD_SQL_INSTANCES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud sql instances describe \- displays configuration and metadata about a Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql instances describe\fR \fIINSTANCE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Displays configuration and metadata about a Cloud SQL instance.

Information such as instance name, IP address, region, the CA certificate and
configuration settings will be displayed.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
