
.TH "GCLOUD_KMS_LOCATIONS" 1



.SH "NAME"
.HP
gcloud kms locations \- view locations available for a project



.SH "SYNOPSIS"
.HP
\f5gcloud kms locations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

View locations available for a project.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlist\fR
List the project's locations.
.RE
.sp
