
.TH "GCLOUD_ORGANIZATIONS" 1



.SH "NAME"
.HP
gcloud organizations \- create and manage Google Cloud Platform Organizations



.SH "SYNOPSIS"
.HP
\f5gcloud organizations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

The gcloud organizations group lets you create and manage Cloud Organizations.
Google Cloud Platform resources form a hierarchy with Organizations at the root.
Organizations contain projects, and Projects contain the remaining Google Cloud
Platform resources.

More information on the Cloud Platform Resource Hierarchy and the Organization
resource can be found here:
https://cloud.google.com/resource\-manager/docs/creating\-managing\-organization
and detailed documentation on creating and managing organizations can be found
here:
https://cloud.google.com/resource\-manager/docs/creating\-managing\-organization



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-iam\-policy\-binding\fR
Add IAM policy binding for a organization.

.TP 2m
\fBdescribe\fR
Show metadata for an organization.

.TP 2m
\fBget\-iam\-policy\fR
Get IAM policy for an organization.

.TP 2m
\fBlist\fR
List organizations accessible by the active account.

.TP 2m
\fBremove\-iam\-policy\-binding\fR
Remove IAM policy binding for a organization.

.TP 2m
\fBset\-iam\-policy\fR
Set IAM policy for an organization.
.RE
.sp
