
.TH "GCLOUD_COMPONENTS_REPOSITORIES_ADD" 1



.SH "NAME"
.HP
gcloud components repositories add \- add a new Trusted Tester component repository



.SH "SYNOPSIS"
.HP
\f5gcloud components repositories add\fR \fIURL\fR [\fIURL\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Add a new Trusted Tester component repository to the list of repositories used
by the component manager. This will allow you to install and update components
found in this repository.

If you are participating in a Trusted Tester program, you will be instructed on
the location of repositories with additional versions of one or more Cloud SDK
components.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIURL\fR [\fIURL\fR ...]
One or more URLs for the component repositories you want to add.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To add the Trusted Tester component repository http://repo.location.com run:

.RS 2m
$ gcloud components repositories add http://repo.location.com
.RE
