
.TH "GCLOUD_COMPUTE_INSTANCE\-GROUPS_MANAGED_WAIT\-UNTIL\-STABLE" 1



.SH "NAME"
.HP
gcloud compute instance\-groups managed wait\-until\-stable \- waits until state of managed instance group is stable



.SH "SYNOPSIS"
.HP
\f5gcloud compute instance\-groups managed wait\-until\-stable\fR \fINAME\fR [\fB\-\-timeout\fR=\fITIMEOUT\fR] [\fB\-\-region\fR=\fIREGION\fR\ |\ \fB\-\-zone\fR=\fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Waits until state of managed instance group is stable.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the managed instance group to operate on.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-timeout\fR=\fITIMEOUT\fR
Timeout in seconds for waiting for group becoming stable.

.RE
.sp
At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region of the managed instance group to operate on. If not specified, you
will be prompted to select a region.

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

Overrides the default \fBcompute/region\fR property value for this command
invocation.

.TP 2m
\fB\-\-zone\fR=\fIZONE\fR
The zone of the managed instance group to operate on. If not specified, you may
be prompted to select a zone.

A list of zones can be fetched by running:

.RS 2m
$ gcloud compute zones list
.RE

Overrides the default \fBcompute/zone\fR property value for this command
invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
