
.TH "GCLOUD_SERVICE\-MANAGEMENT_GET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud service\-management get\-iam\-policy \- describes the IAM policy for a service



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management get\-iam\-policy\fR \fISERVICE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Gets the IAM policy for a produced service, given the service name.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISERVICE\fR
The name of the service whose IAM policy is to be described.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To print the IAM policy for a service named \f5my\-service\fR, run:

.RS 2m
$ gcloud service\-management get\-iam\-policy my\-service
.RE
