
.TH "GCLOUD_DNS_RECORD\-SETS_CHANGES" 1



.SH "NAME"
.HP
gcloud dns record\-sets changes \- view details about changes to your Cloud DNS record\-sets



.SH "SYNOPSIS"
.HP
\f5gcloud dns record\-sets changes\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

View details about changes to your Cloud DNS record\-sets.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
View the details of a change.

.TP 2m
\fBlist\fR
View the list of changes that have been made to your record\-sets.


.RE
.sp

.SH "EXAMPLES"

To view the details of a particular change, run:

.RS 2m
$ gcloud dns record\-sets changes describe CHANGE_ID \e
    \-\-zone MANAGED_ZONE
.RE

To view the list of all changes, run:

.RS 2m
$ gcloud dns record\-sets changes list \-\-zone MANAGED_ZONE
.RE
