
.TH "GCLOUD_SERVICE\-MANAGEMENT_OPERATIONS_WAIT" 1



.SH "NAME"
.HP
gcloud service\-management operations wait \- waits for an operation to complete



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management operations wait\fR \fIOPERATION\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command will block until an operation has been marked as complete.

Note that the \f5operations/\fR prefix of the operation name is optional and may
be omitted.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR
The name of the operation on which to wait.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To wait on an operation named \f5operations/serviceConfigs.my\-service.1\fR to
complete, run:

.RS 2m
$ gcloud service\-management operations wait \e
    serviceConfigs.my\-service.1
.RE
