
.TH "GCLOUD_COMPUTE_TARGET\-VPN\-GATEWAYS_DELETE" 1



.SH "NAME"
.HP
gcloud compute target\-vpn\-gateways delete \- delete target vpn gateways



.SH "SYNOPSIS"
.HP
\f5gcloud compute target\-vpn\-gateways delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute target\-vpn\-gateways delete\fR deletes one or more Google
Compute Engine target vpn gateways.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The names of the Target VPN Gateways to delete.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region of the Target VPN Gateways to delete. If not specified, you will be
prompted to select a region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
