
.TH "GCLOUD_IAM" 1



.SH "NAME"
.HP
gcloud iam \- manage IAM service accounts and keys



.SH "SYNOPSIS"
.HP
\f5gcloud iam\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

The gcloud iam command group lets you manage Google Cloud Identity & Access
Management (IAM) service accounts and keys.

Cloud IAM authorizes who can take action on specific resources, giving you full
control and visibility to manage cloud resources centrally. For established
enterprises with complex organizational structures, hundreds of workgroups and
potentially many more projects, Cloud IAM provides a unified view into security
policy across your entire organization, with built\-in auditing to ease
compliance processes.

More information on Cloud IAM can be found here: https://cloud.google.com/iam
and detailed documentation can be found here: https://cloud.google.com/iam/docs/



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBservice\-accounts\fR
Create and manipulate service accounts.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlist\-grantable\-roles\fR
List IAM grantable roles for a resource.
.RE
.sp
