
.TH "GCLOUD_COMPUTE_XPN_ENABLE" 1



.SH "NAME"
.HP
gcloud compute xpn enable \- enable the given project as an XPN host



.SH "SYNOPSIS"
.HP
\f5gcloud compute xpn enable\fR \fIPROJECT_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

That is, after running this command, one \fBcan\fR enable another project to use
this project via XPN.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIPROJECT_ID\fR
ID for the project to enable as an XPN host


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To enable the project \f5myproject\fR as an XPN host, run:

.RS 2m
$ gcloud compute xpn enable myproject
.RE
