
.TH "GCLOUD_SQL_DATABASES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud sql databases describe \- displays configuration and metadata about a Cloud SQL database



.SH "SYNOPSIS"
.HP
\f5gcloud sql databases describe\fR \fIDATABASE\fR \fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Information such as database name, charset, and collation will be displayed.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIDATABASE\fR
Cloud SQL database name.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
