
.TH "GCLOUD_COMPUTE_ROUTERS_ADD\-BGP\-PEER" 1



.SH "NAME"
.HP
gcloud compute routers add\-bgp\-peer \- add a BGP peer to a Google Compute Engine router



.SH "SYNOPSIS"
.HP
\f5gcloud compute routers add\-bgp\-peer\fR \fINAME\fR \fB\-\-interface\fR=\fIINTERFACE\fR \fB\-\-peer\-asn\fR=\fIPEER_ASN\fR \fB\-\-peer\-name\fR=\fIPEER_NAME\fR [\fB\-\-advertised\-route\-priority\fR=\fIADVERTISED_ROUTE_PRIORITY\fR] [\fB\-\-peer\-ip\-address\fR=\fIPEER_IP_ADDRESS\fR] [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute routers add\-bgp\-peer\fR is used to add a BGP peer to a
Google Compute Engine router.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the router to update.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-interface\fR=\fIINTERFACE\fR
The name of the interface of the peer being added.

.TP 2m
\fB\-\-peer\-asn\fR=\fIPEER_ASN\fR
The asn of the peer being added.

.TP 2m
\fB\-\-peer\-name\fR=\fIPEER_NAME\fR
The name of the peer being added.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-advertised\-route\-priority\fR=\fIADVERTISED_ROUTE_PRIORITY\fR
The priority of routes advertised to this BGP peer. In the case where there is
more than one matching route of maximum length, the routes with lowest priority
value win. 0 <= priority <= 65535.

.TP 2m
\fB\-\-peer\-ip\-address\fR=\fIPEER_IP_ADDRESS\fR
The link local address of the peer.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region of the router to update. If not specified, you will be prompted to
select a region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
