
.TH "GCLOUD_APP_INSTANCES" 1



.SH "NAME"
.HP
gcloud app instances \- view and manage your App Engine instances



.SH "SYNOPSIS"
.HP
\f5gcloud app instances\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This set of commands can be used to view and manage your existing App Engine
instances.

For more information on App Engine instances, see:
https://cloud.google.com/appengine/docs/python/an\-overview\-of\-app\-engine



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdelete\fR
Delete a specified instance.

.TP 2m
\fBdescribe\fR
Display all data about an existing instance.

.TP 2m
\fBdisable\-debug\fR
Disables debug mode for an instance.

.TP 2m
\fBenable\-debug\fR
Enables debug mode for an instance.

.TP 2m
\fBlist\fR
List the instances affiliated with the current App Engine project.

.TP 2m
\fBscp\fR
SCP from or to the VM of an App Engine Flexible instance.

.TP 2m
\fBssh\fR
SSH into the VM of an App Engine Flexible instance.


.RE
.sp

.SH "EXAMPLES"

To list your App Engine instances, run:

.RS 2m
$ gcloud app instances list
.RE
