
.TH "GCLOUD_COMPUTE_TARGET\-POOLS" 1



.SH "NAME"
.HP
gcloud compute target\-pools \- control Compute Engine target pools for network load balancing



.SH "SYNOPSIS"
.HP
\f5gcloud compute target\-pools\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Control Compute Engine target pools for network load balancing.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-health\-checks\fR
Add an HTTP health check to a target pool.

.TP 2m
\fBadd\-instances\fR
Add instances to a target pool.

.TP 2m
\fBcreate\fR
Define a load\-balanced pool of virtual machine instances.

.TP 2m
\fBdelete\fR
Delete target pools.

.TP 2m
\fBdescribe\fR
Describe a Google Compute Engine target pool.

.TP 2m
\fBget\-health\fR
Get the health of instances in a target pool.

.TP 2m
\fBlist\fR
List Google Compute Engine target pools.

.TP 2m
\fBremove\-health\-checks\fR
Remove an HTTP health check from a target pool.

.TP 2m
\fBremove\-instances\fR
Remove instances from a target pool.

.TP 2m
\fBset\-backup\fR
Set a backup pool for a target pool.
.RE
.sp
