
.TH "GCLOUD_CONTAINER_OPERATIONS" 1



.SH "NAME"
.HP
gcloud container operations \- get and list operations for Google Container Engine clusters



.SH "SYNOPSIS"
.HP
\f5gcloud container operations\fR \fICOMMAND\fR [\fB\-\-zone\fR=\fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Get and list operations for Google Container Engine clusters.



.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-zone\fR=\fIZONE\fR, \fB\-z\fR \fIZONE\fR
The compute zone (e.g. us\-central1\-a) for the cluster. Overrides the default
\fBcompute/zone\fR property value for this command invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Describe an operation.

.TP 2m
\fBlist\fR
List operations for container clusters.

.TP 2m
\fBwait\fR
Poll an operation for completion.
.RE
.sp
