
.TH "GCLOUD_SPANNER_DATABASES_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud spanner databases set\-iam\-policy \- set the IAM policy for a Cloud Spanner database



.SH "SYNOPSIS"
.HP
\f5gcloud spanner databases set\-iam\-policy\fR \fIDATABASE\fR \fIPOLICY_FILE\fR \fB\-\-instance\fR=\fIINSTANCE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Set the IAM policy for a Cloud Spanner database.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIDATABASE\fR
Cloud Spanner database ID.

.TP 2m
\fIPOLICY_FILE\fR
Name of JSON or YAML file with the IAM policy.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR
Cloud Spanner instance ID.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
