
.TH "GCLOUD_SQL_BACKUPS_RESTORE" 1



.SH "NAME"
.HP
gcloud sql backups restore \- restores a backup of a Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql backups restore\fR \fIBACKUP_ID\fR \fB\-\-restore\-instance\fR=\fIRESTORE_INSTANCE\fR [\fB\-\-async\fR] [\fB\-\-backup\-instance\fR=\fIBACKUP_INSTANCE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Restores a backup of a Cloud SQL instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIBACKUP_ID\fR
The ID of the backup run to restore from.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-restore\-instance\fR=\fIRESTORE_INSTANCE\fR
Cloud SQL instance ID that will be restored.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Do not wait for the operation to complete.

.TP 2m
\fB\-\-backup\-instance\fR=\fIBACKUP_INSTANCE\fR
The ID of the instance that the backup was taken from.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
