
.TH "GCLOUD_COMPUTE_URL\-MAPS" 1



.SH "NAME"
.HP
gcloud compute url\-maps \- list, create, and delete URL maps



.SH "SYNOPSIS"
.HP
\f5gcloud compute url\-maps\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

List, create, and delete URL maps.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-host\-rule\fR
Add a rule to a URL map to map hosts to a path matcher.

.TP 2m
\fBadd\-path\-matcher\fR
Add a path matcher to a URL map.

.TP 2m
\fBcreate\fR
Create a URL map.

.TP 2m
\fBdelete\fR
Delete URL maps.

.TP 2m
\fBdescribe\fR
Describe a URL map.

.TP 2m
\fBedit\fR
Modify URL maps.

.TP 2m
\fBinvalidate\-cdn\-cache\fR
Invalidate specified objects for a URL map in Cloud CDN caches.

.TP 2m
\fBlist\fR
List Google Compute Engine URL maps.

.TP 2m
\fBlist\-cdn\-cache\-invalidations\fR
List Cloud CDN cache invalidations for a URL map.

.TP 2m
\fBremove\-host\-rule\fR
Remove a host rule from a URL map.

.TP 2m
\fBremove\-path\-matcher\fR
Remove a path matcher from a URL map.

.TP 2m
\fBset\-default\-service\fR
Change the default service or default bucket of a URL map.
.RE
.sp
