
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_KEYS_CREATE" 1



.SH "NAME"
.HP
gcloud iam service\-accounts keys create \- create a private key for a service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts keys create\fR \fIOUTPUT\-FILE\fR \fB\-\-iam\-account\fR=\fIIAM_ACCOUNT\fR [\fB\-\-key\-file\-type\fR=\fIKEY_FILE_TYPE\fR;\ default="json"] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Create a private key for a service account.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOUTPUT\-FILE\fR
The path where the resulting private key should be written.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-iam\-account\fR=\fIIAM_ACCOUNT\fR
The service account for which to create a key.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-key\-file\-type\fR=\fIKEY_FILE_TYPE\fR; default="json"
The type of key to create. \fIKEY_FILE_TYPE\fR must be one of: \fBjson\fR,
\fBp12\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To create a new private key for a service account, and save a copy of it
locally, run:

.RS 2m
$ gcloud iam service\-accounts keys create \e
    \-\-iam\-account my\-iam\-account@somedomain.com key.json
.RE



.SH "NOTES"

The option \-\-key\-file\-type=p12 is available here only for legacy reasons;
all new use cases are encouraged to use the default 'json' format.

