
.TH "GCLOUD_COMPUTE_XPN_ASSOCIATED\-PROJECTS_ADD" 1



.SH "NAME"
.HP
gcloud compute xpn associated\-projects add \- associate the given project with a given host project via XPN



.SH "SYNOPSIS"
.HP
\f5gcloud compute xpn associated\-projects add\fR \fIPROJECT_ID\fR \fB\-\-host\-project\fR=\fIHOST_PROJECT\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Associate the given project with a given host project via XPN.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIPROJECT_ID\fR
ID for the project to add to the host project


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-host\-project\fR=\fIHOST_PROJECT\fR
The XPN host to add an associated project to


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To enable the project \f5xpn\-user\fR to use the project \f5xpn\-host\fR via
XPN, run:

.RS 2m
$ gcloud compute xpn associated\-projects add \e
    \-\-host\-project=xpn\-host xpn\-user
.RE
