
.TH "GCLOUD_DEPLOYMENT\-MANAGER_DEPLOYMENTS" 1



.SH "NAME"
.HP
gcloud deployment\-manager deployments \- commands for Deployment Manager deployments



.SH "SYNOPSIS"
.HP
\f5gcloud deployment\-manager deployments\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Commands to create, update, delete, and examine deployments of resources.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcancel\-preview\fR
Cancel a pending or running deployment preview.

.TP 2m
\fBcreate\fR
Create a deployment.

.TP 2m
\fBdelete\fR
Delete a deployment.

.TP 2m
\fBdescribe\fR
Provide information about a deployment.

.TP 2m
\fBlist\fR
List deployments in a project.

.TP 2m
\fBstop\fR
Stop a pending or running deployment update or creation.

.TP 2m
\fBupdate\fR
Update a deployment based on a provided config file.


.RE
.sp

.SH "EXAMPLES"

To create a deployment, run:

.RS 2m
$ gcloud deployment\-manager deployments create my\-deployment \e
    \-\-config config.yaml
.RE

To update a deployment, run:

.RS 2m
$ gcloud deployment\-manager deployments update my\-deployment \e
    \-\-config new_config.yaml
.RE

To stop a deployment create or update in progress, run:

.RS 2m
$ gcloud deployment\-manager deployments stop my\-deployment
.RE

To cancel a previewed create or update, run:

.RS 2m
$ gcloud deployment\-manager deployments cancel\-preview my\-deployment
.RE

To delete a deployment, run:

.RS 2m
$ gcloud deployment\-manager deployments delete my\-deployment
.RE

To view the details of a deployment, run:

.RS 2m
$ gcloud deployment\-manager deployments describe my\-deployment
.RE

To see the list of all deployments, run:

.RS 2m
$ gcloud deployment\-manager deployments list
.RE
