
.TH "GCLOUD_FIREBASE" 1



.SH "NAME"
.HP
gcloud firebase \- work with Google Firebase



.SH "SYNOPSIS"
.HP
\f5gcloud firebase\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

To view all options available for using Firebase Test Lab, run:

.RS 2m
$ gcloud firebase test \-\-help
.RE



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBtest\fR
Interact with Firebase Test Lab.
.RE
.sp
