
.TH "GCLOUD_ORGANIZATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud organizations describe \- show metadata for an organization



.SH "SYNOPSIS"
.HP
\f5gcloud organizations describe\fR \fIORGANIZATION_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Shows metadata for an organization, given a valid organization ID.

This command can fail for the following reasons:
.RS 2m
.IP "\(bu" 2m
The organization specified does not exist.
.IP "\(bu" 2m
The active account does not have permission to access the given organization.
.RE
.sp



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIORGANIZATION_ID\fR
ID for the organization you want to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

The following command prints metadata for an organization with the ID
\f53589215982\fR:

.RS 2m
$ gcloud organizations describe 3589215982
.RE
