
.TH "GCLOUD_CONFIG_CONFIGURATIONS_ACTIVATE" 1



.SH "NAME"
.HP
gcloud config configurations activate \- activates an existing named configuration



.SH "SYNOPSIS"
.HP
\f5gcloud config configurations activate\fR \fICONFIGURATION_NAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Activates an existing named configuration.

See \f5gcloud topic configurations\fR for an overview of named configurations.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fICONFIGURATION_NAME\fR
Name of the configuration to activate


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To activate an existing named configuration, run:

.RS 2m
$ gcloud config configurations activate my_config
.RE

To list all properties in the activated configuration, run:

.RS 2m
$ gcloud config list \-\-all
.RE
