
.TH "GCLOUD_DATAFLOW_JOBS_CANCEL" 1



.SH "NAME"
.HP
gcloud dataflow jobs cancel \- cancels all jobs that match the command line arguments



.SH "SYNOPSIS"
.HP
\f5gcloud dataflow jobs cancel\fR \fIJOB_ID\fR [\fIJOB_ID\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Cancels all jobs that match the command line arguments.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB_ID\fR [\fIJOB_ID\fR ...]
The job IDs to operate on.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
