
.TH "GCLOUD_VERSION" 1



.SH "NAME"
.HP
gcloud version \- print version information for Cloud SDK components



.SH "SYNOPSIS"
.HP
\f5gcloud version\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

The gcloud version command prints version information for each installed Cloud
SDK components and prints a message if updates are available.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
