
.TH "GCLOUD_ML\-ENGINE_LOCAL" 1



.SH "NAME"
.HP
gcloud ml\-engine local \- cloud ML Engine Local commands



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine local\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Cloud ML Engine Local commands.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBpredict\fR
Run prediction locally.

.TP 2m
\fBtrain\fR
Run a Cloud ML Engine training job locally.
.RE
.sp
