
.TH "GCLOUD_DATAFLOW_JOBS_SHOW" 1



.SH "NAME"
.HP
gcloud dataflow jobs show \- shows a short description of the given job



.SH "SYNOPSIS"
.HP
\f5gcloud dataflow jobs show\fR \fIJOB_ID\fR [\fB\-\-environment\fR] [\fB\-\-steps\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Shows a short description of the given job.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB_ID\fR
The job ID to operate on.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-environment\fR
If present, the environment will be listed.

.TP 2m
\fB\-\-steps\fR
If present, the steps will be listed.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
