
.TH "GCLOUD_COMPUTE_HEALTH\-CHECKS_CREATE" 1



.SH "NAME"
.HP
gcloud compute health\-checks create \- create health checks for load balanced instances



.SH "SYNOPSIS"
.HP
\f5gcloud compute health\-checks create\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Create health checks for load balanced instances.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBhttp\fR
Create a HTTP health check to monitor load balanced instances.

.TP 2m
\fBhttps\fR
Create a HTTPS health check to monitor load balanced instances.

.TP 2m
\fBssl\fR
Create a SSL health check to monitor load balanced instances.

.TP 2m
\fBtcp\fR
Create a TCP health check to monitor load balanced instances.
.RE
.sp
