
.TH "GCLOUD_SPANNER" 1



.SH "NAME"
.HP
gcloud spanner \- command groups for Cloud Spanner



.SH "SYNOPSIS"
.HP
\f5gcloud spanner\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Command groups for Cloud Spanner.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdatabases\fR
Manage Cloud Spanner databases.

.TP 2m
\fBinstance\-configs\fR
Manage Cloud Spanner instance configs.

.TP 2m
\fBinstances\fR
Manage Cloud Spanner instances.

.TP 2m
\fBoperations\fR
Manage Cloud Spanner operations.
.RE
.sp
