
.TH "GCLOUD_SQL_USERS_DELETE" 1



.SH "NAME"
.HP
gcloud sql users delete \- deletes a Cloud SQL user in a given instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql users delete\fR \fIUSERNAME\fR \fIHOST\fR \fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR [\fB\-\-async\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Deletes a Cloud SQL user in a given instance specified by username and host.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIUSERNAME\fR
Cloud SQL username.

.TP 2m
\fIHOST\fR
Cloud SQL user's host.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress, without waiting for the
operation to complete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
