
.TH "GCLOUD_CONFIG_CONFIGURATIONS_CREATE" 1



.SH "NAME"
.HP
gcloud config configurations create \- creates a new named configuration



.SH "SYNOPSIS"
.HP
\f5gcloud config configurations create\fR \fICONFIGURATION_NAME\fR [\fB\-\-no\-activate\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Creates a new named configuration.

Except for special cases (NONE), configuration names start with a lower case
letter and contain only lower case letters a\-z, digits 0\-9, and hyphens '\-'.

See \f5gcloud topic configurations\fR for an overview of named configurations.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fICONFIGURATION_NAME\fR
Name of the configuration to create


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-activate\fR
If true, activate this configuration upon create. Enabled by default, use
\fB\-\-no\-activate\fR to disable.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To create a new named configuration, run:

.RS 2m
$ gcloud config configurations create my\-config
.RE
