
.TH "GCLOUD_COMPUTE_ADDRESSES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute addresses describe \- display detailed information about an address



.SH "SYNOPSIS"
.HP
\f5gcloud compute addresses describe\fR \fINAME\fR [\fB\-\-global\fR\ |\ \fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute addresses describe\fR displays all data associated with an
address in a project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the address to describe.


.RE
.sp

.SH "FLAGS"

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-global\fR
If provided, it is assumed the address is global.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region of the address to describe. Overrides the default
\fBcompute/region\fR property value for this command invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To get details about a global address, run:

.RS 2m
$ gcloud compute addresses describe ADDRESS \-\-global
.RE

To get details about a regional address, run:

.RS 2m
$ gcloud compute addresses describe ADDRESS \-\-region us\-central1
.RE
