
.TH "GCLOUD_COMPUTE_INSTANCE\-GROUPS_MANAGED" 1



.SH "NAME"
.HP
gcloud compute instance\-groups managed \- read and manipulate Google Compute Engine managed instance groups



.SH "SYNOPSIS"
.HP
\f5gcloud compute instance\-groups managed\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Read and manipulate Google Compute Engine managed instance groups.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBabandon\-instances\fR
Abandon instances owned by a managed instance group.

.TP 2m
\fBcreate\fR
Create a Compute Engine managed instance group.

.TP 2m
\fBdelete\fR
Delete Google Compute Engine managed instance groups.

.TP 2m
\fBdelete\-instances\fR
Delete instances managed by managed instance group.

.TP 2m
\fBdescribe\fR
Display detailed information about an instance group.

.TP 2m
\fBget\-named\-ports\fR
Lists the named ports for an instance group resource.

.TP 2m
\fBlist\fR
List Google Compute Engine managed instance groups.

.TP 2m
\fBlist\-instances\fR
List instances present in the managed instance group.

.TP 2m
\fBrecreate\-instances\fR
Recreate instances managed by a managed instance group.

.TP 2m
\fBresize\fR
Set managed instance group size.

.TP 2m
\fBset\-autoscaling\fR
Set autoscaling parameters of a managed instance group.

.TP 2m
\fBset\-instance\-template\fR
Set instance template for managed instance group.

.TP 2m
\fBset\-named\-ports\fR
Sets the list of named ports for an instance group.

.TP 2m
\fBset\-target\-pools\fR
Set target pools of managed instance group.

.TP 2m
\fBstop\-autoscaling\fR
Stop autoscaling a managed instance group.

.TP 2m
\fBwait\-until\-stable\fR
Waits until state of managed instance group is stable.
.RE
.sp
