
.TH "GCLOUD_SQL_BACKUPS_DELETE" 1



.SH "NAME"
.HP
gcloud sql backups delete \- delete a backup of a Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql backups delete\fR \fIID\fR \fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR [\fB\-\-async\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete a backup of a Cloud SQL instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIID\fR
The ID of the backup run. You can find the ID by running $ gcloud beta sql
backups list.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress, without waiting for the
operation to complete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
