
.TH "GCLOUD_AUTH_REVOKE" 1



.SH "NAME"
.HP
gcloud auth revoke \- revoke access credentials for an account



.SH "SYNOPSIS"
.HP
\f5gcloud auth revoke\fR [\fIACCOUNTS\fR\ ...] [\fB\-\-all\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Revokes credentials for the specified user accounts or service accounts. When
you revoke the credentials, they are removed from the local machine. If no
account is specified, this command revokes credentials for the currently active
account.

You can revoke credentials when you want to disallow access by gcloud and other
Cloud SDK tools using a specified account. You don't need to revoke credentials
to switch between accounts.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
[\fIACCOUNTS\fR ...]
Accounts whose credentials are to be revoked.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-all\fR
Revoke credentials for all accounts.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
