
.TH "GCLOUD_SQL_INSTANCES_IMPORT" 1



.SH "NAME"
.HP
gcloud sql instances import \- imports data into a Cloud SQL instance from Google Cloud Storage



.SH "SYNOPSIS"
.HP
\f5gcloud sql instances import\fR \fIINSTANCE\fR \fIURI\fR [\fB\-\-async\fR] [\fB\-\-database\fR=\fIDATABASE\fR,\ \fB\-d\fR\ \fIDATABASE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Note: authorization is required. For more information on importing data into
Google Cloud SQL see https://cloud.google.com/sql/docs/import\-export/importing.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR
Cloud SQL instance ID.

.TP 2m
\fIURI\fR
Path to the MySQL dump file in Google Cloud Storage from which the import is
made. The URI is in the form gs://bucketName/fileName. Compressed gzip files
(.gz) are also supported.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Do not wait for the operation to complete.

.TP 2m
\fB\-\-database\fR=\fIDATABASE\fR, \fB\-d\fR \fIDATABASE\fR
The database (for example, guestbook) to which the import is made. If not set,
it is assumed that the database is specified in the file to be imported.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
