
.TH "GCLOUD_CONTAINER_BUILDS_CANCEL" 1



.SH "NAME"
.HP
gcloud container builds cancel \- cancel an ongoing build



.SH "SYNOPSIS"
.HP
\f5gcloud container builds cancel\fR \fIBUILD\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Cancel an ongoing build.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIBUILD\fR
The build to cancel. The ID of the build is printed at the end of the build
submission process, or in the ID column when listing builds.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
