
.TH "GCLOUD_SOURCE_REPOS_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud source repos set\-iam\-policy \- set the IAM policy for the named repository



.SH "SYNOPSIS"
.HP
\f5gcloud source repos set\-iam\-policy\fR \fIREPOSITORY_NAME\fR \fIPOLICY_FILE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command sets the IAM policy for the given repository from the policy in the
provided file.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIREPOSITORY_NAME\fR
Name of the repository.

.TP 2m
\fIPOLICY_FILE\fR
JSON file with IAM policy. See
https://cloud.google.com/resource\-manager/reference/rest/Shared.Types/Policy


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To set the IAM policy, issue the following command:

.RS 2m
$ gcloud source repos set\-iam\-policy REPOSITORY_NAME POLICY_FILE
.RE
