
.TH "GCLOUD_DEPLOYMENT\-MANAGER_OPERATIONS_LIST" 1



.SH "NAME"
.HP
gcloud deployment\-manager operations list \- list operations in a project



.SH "SYNOPSIS"
.HP
\f5gcloud deployment\-manager operations list\fR [\fB\-\-simple\-list\fR] [\fB\-\-filter\fR=\fIEXPRESSION\fR] [\fB\-\-limit\fR=\fILIMIT\fR] [\fB\-\-page\-size\fR=\fIPAGE_SIZE\fR] [\fB\-\-sort\-by\fR=[\fIFIELD\fR,...]] [\fB\-\-uri\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Prints a table with summary information on all operations in the project.



.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-simple\-list\fR
Changes the \-\-format flag to print the resource IDs. Otherwise either the
\-\-format value or the default format is used.


.RE
.sp

.SH "LIST COMMAND FLAGS"

.RS 2m
.TP 2m
\fB\-\-filter\fR=\fIEXPRESSION\fR
Apply a Boolean filter \fIEXPRESSION\fR to each resource item to be listed. If
the expression evaluates True then that item is listed. For more details and
examples of filter expressions run $ gcloud topic filters. This flag interacts
with other flags that are applied in this order: \fB\-\-flatten\fR,
\fB\-\-sort\-by\fR, \fB\-\-filter\fR, \fB\-\-limit\fR.

.TP 2m
\fB\-\-limit\fR=\fILIMIT\fR
The maximum number of resources to list. The default is \fBunlimited\fR. This
flag interacts with other flags that are applied in this order:
\fB\-\-flatten\fR, \fB\-\-sort\-by\fR, \fB\-\-filter\fR, \fB\-\-limit\fR.

.TP 2m
\fB\-\-page\-size\fR=\fIPAGE_SIZE\fR
Some services group resource list output into pages. This flag specifies the
maximum number of resources per page. The default is determined by the service
if it supports paging, otherwise it is \fBunlimited\fR (no paging). Paging may
be applied before or after \fB\-\-filter\fR and \fB\-\-limit\fR depending on the
service.

.TP 2m
\fB\-\-sort\-by\fR=[\fIFIELD\fR,...]
A comma\-separated list of resource field key names to sort by. The default
order is ascending. Prefix a field with ``~'' for descending order on that
field. This flag interacts with other flags that are applied in this order:
\fB\-\-flatten\fR, \fB\-\-sort\-by\fR, \fB\-\-filter\fR, \fB\-\-limit\fR.

.TP 2m
\fB\-\-uri\fR
Print a list of resource URIs instead of the default output.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To print out a list of operations with some summary information about each, run:

.RS 2m
$ gcloud deployment\-manager operations list
.RE

To print only the name of each operation, run:

.RS 2m
$ gcloud deployment\-manager operations list \-\-simple\-list
.RE
