
.TH "GCLOUD_SERVICE\-MANAGEMENT_OPERATIONS" 1



.SH "NAME"
.HP
gcloud service\-management operations \- manage Operation for various services



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management operations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Operation for various services.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Describes an operation resource for a given operation name.

.TP 2m
\fBwait\fR
Waits for an operation to complete.
.RE
.sp
