
.TH "GCLOUD_SQL_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud sql operations describe \- retrieves information about a Cloud SQL instance operation



.SH "SYNOPSIS"
.HP
\f5gcloud sql operations describe\fR \fIOPERATION\fR [\fB\-\-instance\fR=\fIINSTANCE\fR,\ \fB\-i\fR\ \fIINSTANCE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Retrieves information about a Cloud SQL instance operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR
Name that uniquely identifies the operation.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
(DEPRECATED) Cloud SQL instance ID.

Starting on 2017\-06\-30, \-\-instance will no longer be a valid flag: Run the
same command but omit this flag.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
