
.TH "GCLOUD_SQL_CONNECT" 1



.SH "NAME"
.HP
gcloud sql connect \- connects to a Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql connect\fR \fIINSTANCE\fR [\fB\-\-user\fR=\fIUSER\fR,\ \fB\-u\fR\ \fIUSER\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Connects to a Cloud SQL instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-user\fR=\fIUSER\fR, \fB\-u\fR \fIUSER\fR
Cloud SQL instance user to connect as.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To connect to a Cloud SQL instance, run:

.RS 2m
$ gcloud sql connect my\-instance \-\-user=root
.RE
