
.TH "GCLOUD_CONTAINER_CLUSTERS_GET\-CREDENTIALS" 1



.SH "NAME"
.HP
gcloud container clusters get\-credentials \- fetch credentials for a running cluster



.SH "SYNOPSIS"
.HP
\f5gcloud container clusters get\-credentials\fR \fINAME\fR [\fB\-\-zone\fR=\fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Updates a kubeconfig file with appropriate credentials to point kubectl at a
Container Engine Cluster. By default, credentials are written to
HOME/.kube/config. You can provide an alternate path by setting the KUBECONFIG
environment variable.

See https://cloud.google.com/container\-engine/docs/kubectl for kubectl
documentation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the cluster to get credentials for. Overrides the default
\fBcontainer/cluster\fR property value for this command invocation.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-zone\fR=\fIZONE\fR, \fB\-z\fR \fIZONE\fR
The compute zone (e.g. us\-central1\-a) for the cluster. Overrides the default
\fBcompute/zone\fR property value for this command invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
