
.TH "GCLOUD_COMPUTE_PROJECT\-INFO_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute project\-info describe \- describe the Google Compute Engine project resource



.SH "SYNOPSIS"
.HP
\f5gcloud compute project\-info describe\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute project\-info describe\fR displays all data associated with
the Google Compute Engine project resource. The project resource contains data
such as global quotas, common instance metadata, and the project's creation
time.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
