
.TH "GCLOUD_SQL_BACKUPS_CREATE" 1



.SH "NAME"
.HP
gcloud sql backups create \- creates a backup of a Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql backups create\fR \fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR [\fB\-\-async\fR] [\fB\-\-description\fR=\fIDESCRIPTION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Creates a backup of a Cloud SQL instance.



.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Do not wait for the operation to complete.

.TP 2m
\fB\-\-description\fR=\fIDESCRIPTION\fR
A friendly description of the backup.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
