
.TH "GCLOUD_APP_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud app operations describe \- describes the operation



.SH "SYNOPSIS"
.HP
\f5gcloud app operations describe\fR \fIOPERATION\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Describes the operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR
ID of operation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To describe an App Engine operation called o1, run:

.RS 2m
$ gcloud app operations describe o1
.RE
