
.TH "GCLOUD_KMS_KEYRINGS" 1



.SH "NAME"
.HP
gcloud kms keyrings \- create and manage keyrings



.SH "SYNOPSIS"
.HP
\f5gcloud kms keyrings\fR \fICOMMAND\fR [\fB\-\-location\fR=\fILOCATION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

A keyring is a toplevel logical grouping of keys.



.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
The location of the requested resource.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-iam\-policy\-binding\fR
Add IAM policy binding to a keyring.

.TP 2m
\fBcreate\fR
Create a new keyring.

.TP 2m
\fBdescribe\fR
Get metadata for a keyring.

.TP 2m
\fBget\-iam\-policy\fR
Get the IAM policy for a keyring.

.TP 2m
\fBlist\fR
List keyrings within a location.

.TP 2m
\fBremove\-iam\-policy\-binding\fR
Remove a policy binding from a keyring.

.TP 2m
\fBset\-iam\-policy\fR
Set the IAM policy for a keyring.
.RE
.sp
