
.TH "GCLOUD_COMPUTE_INSTANCE\-TEMPLATES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute instance\-templates describe \- describe a virtual machine instance template



.SH "SYNOPSIS"
.HP
\f5gcloud compute instance\-templates describe\fR \fINAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute instance\-templates describe\fR displays all data associated
with a Google Compute Engine virtual machine instance template.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the instance template to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
