
.TH "GCLOUD_SQL_INSTANCES_PROMOTE\-REPLICA" 1



.SH "NAME"
.HP
gcloud sql instances promote\-replica \- promotes Cloud SQL read replica to a stand\-alone instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql instances promote\-replica\fR \fIREPLICA\fR [\fB\-\-async\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Promotes Cloud SQL read replica to a stand\-alone instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIREPLICA\fR
Cloud SQL read replica ID.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress, without waiting for the
operation to complete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
