
.TH "GCLOUD_SQL_USERS" 1



.SH "NAME"
.HP
gcloud sql users \- provide commands for managing Cloud SQL users



.SH "SYNOPSIS"
.HP
\f5gcloud sql users\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Provide commands for managing Cloud SQL users including creating, listing, and
deleting users.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Creates a user in a given instance.

.TP 2m
\fBdelete\fR
Deletes a Cloud SQL user in a given instance.

.TP 2m
\fBlist\fR
Lists Cloud SQL users in a given instance.

.TP 2m
\fBset\-password\fR
Changes a user's password in a given instance.
.RE
.sp
