
.TH "GCLOUD_DEBUG_SOURCE" 1



.SH "NAME"
.HP
gcloud debug source \- commands to manage source information for Stackdriver tools



.SH "SYNOPSIS"
.HP
\f5gcloud debug source\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This set of commands allows you to provide Stackdriver tools with source code
version information.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBgen\-repo\-info\-file\fR
Generates repository information files for the Stackdriver Debugger.
.RE
.sp
