
.TH "GCLOUD_DEBUG_SOURCE_GEN\-REPO\-INFO\-FILE" 1



.SH "NAME"
.HP
gcloud debug source gen\-repo\-info\-file \- generates repository information files for the Stackdriver Debugger



.SH "SYNOPSIS"
.HP
\f5gcloud debug source gen\-repo\-info\-file\fR [\fB\-\-output\-directory\fR=\fIOUTPUT_DIRECTORY\fR;\ default="."] [\fB\-\-source\-directory\fR=\fISOURCE_DIRECTORY\fR;\ default="."] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command generates two files, source\-context.json and
source\-contexts.json, containing information on the source revision and remote
repository associated with the given source directory.



.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-output\-directory\fR=\fIOUTPUT_DIRECTORY\fR; default="."
The directory in which to create the source context files.

.TP 2m
\fB\-\-source\-directory\fR=\fISOURCE_DIRECTORY\fR; default="."
The directory containing the source code for the build.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To generate repository information files for your app, from your source
directory run:

.RS 2m
$ gcloud debug source gen\-repo\-info\-file
.RE
