
.TH "GCLOUD_ML\-ENGINE_OPERATIONS" 1



.SH "NAME"
.HP
gcloud ml\-engine operations \- manage Cloud ML Engine operations



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine operations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud ML Engine operations.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcancel\fR
Cancel a Cloud ML Engine operation.

.TP 2m
\fBdelete\fR
Delete a Cloud ML Engine operation.

.TP 2m
\fBdescribe\fR
Describe a Cloud ML Engine operation.

.TP 2m
\fBlist\fR
List existing Cloud ML Engine jobs.

.TP 2m
\fBwait\fR
Wait for a Cloud ML Engine operation to complete.
.RE
.sp
