
.TH "GCLOUD_DATAPROC_OPERATIONS_CANCEL" 1



.SH "NAME"
.HP
gcloud dataproc operations cancel \- cancel an active operation



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc operations cancel\fR \fIOPERATION\fR [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Cancel an active operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR
The ID of the operation to cancel.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
Specifies the Cloud Dataproc region to use. Each Cloud Dataproc region
constitutes an independent resource namespace constrained to deploying instances
into Google Compute Engine zones inside the region. The default value of
"global" is a special multi\-region namespace which is capable of deploying
instances into all Google Compute Engine zones globally, and is disjoint from
other Cloud Dataproc regions. Overrides the default \fBdataproc/region\fR
property value for this command invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To cancel an operation, run:

.RS 2m
$ gcloud dataproc operations cancel operation_id
.RE
