
.TH "GCLOUD_KMS_KEYS_VERSIONS" 1



.SH "NAME"
.HP
gcloud kms keys versions \- create and manage versions



.SH "SYNOPSIS"
.HP
\f5gcloud kms keys versions\fR \fICOMMAND\fR [\fB\-\-key\fR=\fIKEY\fR] [\fB\-\-keyring\fR=\fIKEYRING\fR] [\fB\-\-location\fR=\fILOCATION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

A version represents an individual cryptographic key and the associated key
material.



.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-key\fR=\fIKEY\fR
The containing key.

.TP 2m
\fB\-\-keyring\fR=\fIKEYRING\fR
The containing keyring.

.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
The location of the requested resource.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create a new version.

.TP 2m
\fBdescribe\fR
Get metadata for a given version.

.TP 2m
\fBdestroy\fR
Schedule a version to be destroyed.

.TP 2m
\fBdisable\fR
Disable a given version.

.TP 2m
\fBenable\fR
Enable a given version.

.TP 2m
\fBlist\fR
List the versions within a key.

.TP 2m
\fBrestore\fR
Restore a version scheduled for destruction.
.RE
.sp
