
.TH "GCLOUD_KMS_KEYS_REMOVE\-ROTATION\-SCHEDULE" 1



.SH "NAME"
.HP
gcloud kms keys remove\-rotation\-schedule \- remove the rotation schedule for a key



.SH "SYNOPSIS"
.HP
\f5gcloud kms keys remove\-rotation\-schedule\fR \fIKEY\fR [\fB\-\-keyring\fR=\fIKEYRING\fR] [\fB\-\-location\fR=\fILOCATION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Removes the rotation schedule for the given key.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIKEY\fR
Name of the key from which to clear the rotation schedule.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-keyring\fR=\fIKEYRING\fR
The containing keyring.

.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
The location of the requested resource.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

The following command removes the rotation schedule for the key named
\f5frodo\fR within the keyring \f5fellowship\fR and location \f5global\fR:

.RS 2m
$ gcloud kms keys remove\-rotation\-schedule frodo \e
    \-\-location global \e
    \-\-keyring fellowship
.RE
