
.TH "GCLOUD_SQL_OPERATIONS" 1



.SH "NAME"
.HP
gcloud sql operations \- provide commands for working with Cloud SQL instance operations



.SH "SYNOPSIS"
.HP
\f5gcloud sql operations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Provide commands for working with Cloud SQL instance operations, including
listing and getting information about instance operations of a Cloud SQL
instance.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Retrieves information about a Cloud SQL instance operation.

.TP 2m
\fBlist\fR
Lists all instance operations for the given Cloud SQL instance.

.TP 2m
\fBwait\fR
Waits for one or more operations to complete.
.RE
.sp
