
.TH "GCLOUD_DEPLOYMENT\-MANAGER_RESOURCES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud deployment\-manager resources describe \- provide information about a resource



.SH "SYNOPSIS"
.HP
\f5gcloud deployment\-manager resources describe\fR \fIRESOURCE\fR [\fB\-\-deployment\fR=\fIDEPLOYMENT\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command prints out all available details about a resource.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIRESOURCE\fR
Resource name.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-deployment\fR=\fIDEPLOYMENT\fR
Deployment name


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To display information about a resource, run:

.RS 2m
$ gcloud deployment\-manager resources describe \e
    \-\-deployment my\-deployment my\-resource\-name
.RE
