
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS" 1



.SH "NAME"
.HP
gcloud iam service\-accounts \- create and manipulate service accounts



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Create and manipulate IAM service accounts. A service account is a special
Google account that belongs to your application or a VM, instead of to an
individual end user. Your application uses the service account to call the
Google API of a service, so that the users aren't directly involved.

Note: Service accounts use client quotas for tracking usage.

More information on service accounts can be found at:
https://cloud.google.com/iam/docs/service\-accounts



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBkeys\fR
Manage service account keys.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-iam\-policy\-binding\fR
Add IAM policy binding for a service account.

.TP 2m
\fBcreate\fR
Create a service account for a project.

.TP 2m
\fBdelete\fR
Delete a service account from a project.

.TP 2m
\fBdescribe\fR
Show metadata for a service account from a project.

.TP 2m
\fBget\-iam\-policy\fR
Get the IAM policy for a service account.

.TP 2m
\fBlist\fR
List all of a project's service accounts.

.TP 2m
\fBremove\-iam\-policy\-binding\fR
Remove IAM policy binding for a service account.

.TP 2m
\fBset\-iam\-policy\fR
Set IAM policy for a service account.

.TP 2m
\fBsign\-blob\fR
Sign a blob with a managed service account key.

.TP 2m
\fBupdate\fR
Update the metadata of an IAM service account.
.RE
.sp
