
.TH "GCLOUD_KMS_KEYS_VERSIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud kms keys versions describe \- get metadata for a given version



.SH "SYNOPSIS"
.HP
\f5gcloud kms keys versions describe\fR \fIVERSION\fR [\fB\-\-key\fR=\fIKEY\fR] [\fB\-\-keyring\fR=\fIKEYRING\fR] [\fB\-\-location\fR=\fILOCATION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Returns metadata for the given version.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIVERSION\fR
Name of the version to describe.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-key\fR=\fIKEY\fR
The containing key.

.TP 2m
\fB\-\-keyring\fR=\fIKEYRING\fR
The containing keyring.

.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
The location of the requested resource.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

The following command returns metadata for version 2 within key \f5frodo\fR
within the keyring \f5fellowship\fR in the location \f5us\-east1\fR:

.RS 2m
$ gcloud kms keys versions describe 2 \-\-key frodo \e
    \-\-keyring fellowship \-\-location us\-east1
.RE
