
.TH "GCLOUD_KMS_KEYRINGS_CREATE" 1



.SH "NAME"
.HP
gcloud kms keyrings create \- create a new keyring



.SH "SYNOPSIS"
.HP
\f5gcloud kms keyrings create\fR \fIKEYRING\fR [\fB\-\-location\fR=\fILOCATION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Creates a new keyring within the given location.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIKEYRING\fR
Name of the keyring to create.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
The location of the requested resource.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
