
.TH "GCLOUD_COMPUTE_HEALTH\-CHECKS" 1



.SH "NAME"
.HP
gcloud compute health\-checks \- read and manipulate health checks for load balanced instances



.SH "SYNOPSIS"
.HP
\f5gcloud compute health\-checks\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Read and manipulate health checks for load balanced instances.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create health checks for load balanced instances.

.TP 2m
\fBupdate\fR
Update health checks for load balanced instances.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdelete\fR
Delete health checks.

.TP 2m
\fBdescribe\fR
Display detailed information about a health check.

.TP 2m
\fBlist\fR
List Google Compute Engine health checks.
.RE
.sp
