
.TH "GCLOUD_CONTAINER_BUILDS" 1



.SH "NAME"
.HP
gcloud container builds \- create and manage container builds



.SH "SYNOPSIS"
.HP
\f5gcloud container builds\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Create and manage container builds.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcancel\fR
Cancel an ongoing build.

.TP 2m
\fBdescribe\fR
Get information about a particular build.

.TP 2m
\fBlist\fR
List builds.

.TP 2m
\fBlog\fR
Stream the logs for a build.

.TP 2m
\fBsubmit\fR
Submit a build using the Google Container Builder service.
.RE
.sp
