
.TH "GCLOUD_APP_OPERATIONS" 1



.SH "NAME"
.HP
gcloud app operations \- view and manage your App Engine Operations



.SH "SYNOPSIS"
.HP
\f5gcloud app operations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This set of commands can be used to view and manage your existing App Engine
operations.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Describes the operation.

.TP 2m
\fBlist\fR
List the operations.

.TP 2m
\fBwait\fR
Polls an operation until completion.


.RE
.sp

.SH "EXAMPLES"

To list your App Engine operations, run:

.RS 2m
$ gcloud app operations list
.RE
