
.TH "GCLOUD_SOURCE_REPOS_CREATE" 1



.SH "NAME"
.HP
gcloud source repos create \- create a cloud source repository



.SH "SYNOPSIS"
.HP
\f5gcloud source repos create\fR \fIREPOSITORY_NAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command creates a named git repository for the currently active Google
Cloud Platform project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIREPOSITORY_NAME\fR
Name of the repository. May contain between 3 and 63 (inclusive) lowercase
letters, digits, and hyphens. Must start with a letter, and may not end with a
hyphen.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To create a named repository in the current project issue the following
commands:

.RS 2m
$ gcloud init
$ gcloud source repos create REPOSITORY_NAME
.RE

Once you push contents to it, they can be browsed in the Developers Console.
