
.TH "GCLOUD_SPANNER_INSTANCE\-CONFIGS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud spanner instance\-configs describe \- describe a Cloud Spanner instance config



.SH "SYNOPSIS"
.HP
\f5gcloud spanner instance\-configs describe\fR \fIINSTANCE_CONFIG\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Describe a Cloud Spanner instance config.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE_CONFIG\fR
Cloud Spanner instance config.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
