
.TH "GCLOUD_DATAFLOW_JOBS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud dataflow jobs describe \- outputs the Job object resulting from the Get API



.SH "SYNOPSIS"
.HP
\f5gcloud dataflow jobs describe\fR \fIJOB_ID\fR [\fB\-\-full\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

By default this will display the Summary view which includes:
.RS 2m
.IP "\(bu" 2m
Project ID
.IP "\(bu" 2m
Job ID
.IP "\(bu" 2m
Job Name
.IP "\(bu" 2m
Job Type (Batch vs. Streaming)
.IP "\(bu" 2m
Job Create Time
.IP "\(bu" 2m
Job Status (Running, Done, Cancelled, Failed)
.IP "\(bu" 2m
Job Status Time
.RE
.sp

Notable values that are only in the full view:
.RS 2m
.IP "\(bu" 2m
Environment (staging Jars, information about workers, etc.)
.IP "\(bu" 2m
Steps from the workflow graph
.RE
.sp



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB_ID\fR
The job ID to operate on.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-full\fR
Retrieve the full Job rather than the summary view


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
