
.TH "GCLOUD_SQL_SSL\-CERTS_CREATE" 1



.SH "NAME"
.HP
gcloud sql ssl\-certs create \- creates an SSL certificate for a Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql ssl\-certs create\fR \fICOMMON_NAME\fR \fICERT_FILE\fR \fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Creates an SSL certificate for a Cloud SQL instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fICOMMON_NAME\fR
User supplied name. Constrained to \f5[a\-zA\-Z.\-_ ]+\fR.

.TP 2m
\fICERT_FILE\fR
Location of file which the private key of the created ssl\-cert will be written
to.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
