
.TH "GCLOUD_ML\-ENGINE_OPERATIONS_WAIT" 1



.SH "NAME"
.HP
gcloud ml\-engine operations wait \- wait for a Cloud ML Engine operation to complete



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine operations wait\fR \fIOPERATION\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Wait for a Cloud ML Engine operation to complete.

Given an operation ID, this command polls the operation and blocks until it
completes. At completion, the operation message is printed (which includes the
operation response).



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR
Name of the operation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
