
.TH "GCLOUD_COMPUTE_URL\-MAPS_DELETE" 1



.SH "NAME"
.HP
gcloud compute url\-maps delete \- delete URL maps



.SH "SYNOPSIS"
.HP
\f5gcloud compute url\-maps delete\fR \fIURL_MAP_NAME\fR [\fIURL_MAP_NAME\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute url\-maps delete\fR deletes one or more URL maps.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIURL_MAP_NAME\fR [\fIURL_MAP_NAME\fR ...]
The names of the URL maps to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
