
.TH "GCLOUD_DNS_MANAGED\-ZONES_DELETE" 1



.SH "NAME"
.HP
gcloud dns managed\-zones delete \- delete an empty Cloud DNS managed\-zone



.SH "SYNOPSIS"
.HP
\f5gcloud dns managed\-zones delete\fR \fIZONE_NAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command deletes an empty Cloud DNS managed\-zone. An empty managed\-zone
has only SOA and NS record\-sets.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIZONE_NAME\fR
The name of the empty managed\-zone to be deleted.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To delete an empty managed\-zone, run:

.RS 2m
$ gcloud dns managed\-zones delete my_zone
.RE
