
.TH "GCLOUD_SQL_FLAGS" 1



.SH "NAME"
.HP
gcloud sql flags \- provide a command to list flags



.SH "SYNOPSIS"
.HP
\f5gcloud sql flags\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Provide a command to list flags.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlist\fR
List customizable flags for Google Cloud SQL instances.
.RE
.sp
