
.TH "GCLOUD_COMPUTE_TARGET\-VPN\-GATEWAYS" 1



.SH "NAME"
.HP
gcloud compute target\-vpn\-gateways \- read and manipulate Google Compute Engine VPN Gateways



.SH "SYNOPSIS"
.HP
\f5gcloud compute target\-vpn\-gateways\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Read and manipulate Google Compute Engine VPN Gateways.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create a target VPN Gateway.

.TP 2m
\fBdelete\fR
Delete target vpn gateways.

.TP 2m
\fBdescribe\fR
Describe a Google Compute Engine target vpn gateway.

.TP 2m
\fBlist\fR
List Google Compute Engine target VPN gateways.
.RE
.sp
