
.TH "GCLOUD_COMPUTE_PROJECT\-INFO" 1



.SH "NAME"
.HP
gcloud compute project\-info \- read and manipulate project\-level data like quotas and metadata



.SH "SYNOPSIS"
.HP
\f5gcloud compute project\-info\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Read and manipulate project\-level data like quotas and metadata.


\f5Note\fR: project\-level metadata is a distinct concept from instance\-level
metadata; for details on instance metadata see:
https://cloud.google.com/compute/docs/storing\-retrieving\-metadata



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-metadata\fR
Add or update project\-wide metadata.

.TP 2m
\fBdescribe\fR
Describe the Google Compute Engine project resource.

.TP 2m
\fBremove\-metadata\fR
Remove project\-wide metadata entries.

.TP 2m
\fBset\-usage\-bucket\fR
Set the usage reporting bucket for a project.
.RE
.sp
