
.TH "GCLOUD_COMPUTE_URL\-MAPS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute url\-maps describe \- describe a URL map



.SH "SYNOPSIS"
.HP
\f5gcloud compute url\-maps describe\fR \fIURL_MAP_NAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute url\-maps describe\fR displays all data associated with a URL
map in a project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIURL_MAP_NAME\fR
The name of the URL map to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
