
.TH "GCLOUD_COMPUTE_ROUTERS_ADD\-INTERFACE" 1



.SH "NAME"
.HP
gcloud compute routers add\-interface \- add an interface to a Google Compute Engine router



.SH "SYNOPSIS"
.HP
\f5gcloud compute routers add\-interface\fR \fINAME\fR \fB\-\-interface\-name\fR=\fIINTERFACE_NAME\fR \fB\-\-vpn\-tunnel\fR=\fIVPN_TUNNEL\fR [\fB\-\-ip\-address\fR=\fIIP_ADDRESS\fR] [\fB\-\-mask\-length\fR=\fIMASK_LENGTH\fR] [\fB\-\-region\fR=\fIREGION\fR] [\fB\-\-vpn\-tunnel\-region\fR=\fIVPN_TUNNEL_REGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute routers add\-interface\fR is used to add an interface to a
Google Compute Engine router.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the router to update.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-interface\-name\fR=\fIINTERFACE_NAME\fR
The name of the interface being added.

.TP 2m
\fB\-\-vpn\-tunnel\fR=\fIVPN_TUNNEL\fR
The tunnel of the interface being added.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-ip\-address\fR=\fIIP_ADDRESS\fR
The link local address of the router for this interface.

.TP 2m
\fB\-\-mask\-length\fR=\fIMASK_LENGTH\fR
The mask for network used for the server IP address.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region of the router to update. If not specified, you will be prompted to
select a region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.

.TP 2m
\fB\-\-vpn\-tunnel\-region\fR=\fIVPN_TUNNEL_REGION\fR
The region of the vpn tunnel to operate on. If not specified it will be set to
the region of the router. Overrides the default \fBcompute/region\fR property
value for this command invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
