
.TH "GCLOUD_COMPUTE_VPN\-TUNNELS" 1



.SH "NAME"
.HP
gcloud compute vpn\-tunnels \- read and manipulate Google Compute Engine VPN Tunnels



.SH "SYNOPSIS"
.HP
\f5gcloud compute vpn\-tunnels\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Read and manipulate Google Compute Engine VPN Tunnels.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create a VPN tunnel.

.TP 2m
\fBdelete\fR
Delete vpn tunnels.

.TP 2m
\fBdescribe\fR
Describe a Google Compute Engine vpn tunnel.

.TP 2m
\fBlist\fR
List Google Compute Engine VPN tunnels.
.RE
.sp
