
.TH "GCLOUD_SOURCE_REPOS_GET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud source repos get\-iam\-policy \- get the IAM policy for the named cloud source repository



.SH "SYNOPSIS"
.HP
\f5gcloud source repos get\-iam\-policy\fR \fIREPOSITORY_NAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command gets the IAM policy for the given repository.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIREPOSITORY_NAME\fR
Name of the repository.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To get the IAM policy, issue the following command:

.RS 2m
$ gcloud source repos get\-iam\-policy REPOSITORY_NAME
.RE
