
.TH "GCLOUD_COMPUTE_BACKEND\-SERVICES" 1



.SH "NAME"
.HP
gcloud compute backend\-services \- list, create, and delete backend services



.SH "SYNOPSIS"
.HP
\f5gcloud compute backend\-services\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

List, create, and delete backend services.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-backend\fR
Add a backend to a backend service.

.TP 2m
\fBcreate\fR
Create a backend service.

.TP 2m
\fBdelete\fR
Delete backend services.

.TP 2m
\fBdescribe\fR
Display detailed information about a backend service.

.TP 2m
\fBedit\fR
Modify backend services.

.TP 2m
\fBget\-health\fR
Get backend health statuses from a backend service.

.TP 2m
\fBlist\fR
List Google Compute Engine backend services.

.TP 2m
\fBremove\-backend\fR
Remove a backend from a backend service.

.TP 2m
\fBupdate\fR
Update a backend service.

.TP 2m
\fBupdate\-backend\fR
Update an existing backend in a backend service.
.RE
.sp
