
.TH "GCLOUD_COMPUTE_DISKS" 1



.SH "NAME"
.HP
gcloud compute disks \- read and manipulate Google Compute Engine disks



.SH "SYNOPSIS"
.HP
\f5gcloud compute disks\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Read and manipulate Google Compute Engine disks.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-labels\fR
Add labels to Google Compute Engine persistent disks.

.TP 2m
\fBcreate\fR
Create Google Compute Engine persistent disks.

.TP 2m
\fBdelete\fR
Delete Google Compute Engine persistent disks.

.TP 2m
\fBdescribe\fR
Describe a Google Compute Engine disk.

.TP 2m
\fBlist\fR
List Google Compute Engine disks.

.TP 2m
\fBmove\fR
Move a disk between zones.

.TP 2m
\fBremove\-labels\fR
Remove labels from Google Compute Engine persistent disks.

.TP 2m
\fBresize\fR
Resize a disk or disks.

.TP 2m
\fBsnapshot\fR
Create snapshots of Google Compute Engine persistent disks.

.TP 2m
\fBupdate\fR
Update a Google Compute Engine persistent disk.
.RE
.sp
