
.TH "GCLOUD_KMS_KEYS_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud kms keys set\-iam\-policy \- set the IAM policy for a key



.SH "SYNOPSIS"
.HP
\f5gcloud kms keys set\-iam\-policy\fR \fIKEY\fR \fIPOLICY_FILE\fR [\fB\-\-keyring\fR=\fIKEYRING\fR] [\fB\-\-location\fR=\fILOCATION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Sets the IAM policy for the given key as defined in a JSON file.

See https://cloud.google.com/iam/docs/managing\-policies for details of the
policy file format and contents.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIKEY\fR
Name of the key whose IAM policy to update.

.TP 2m
\fIPOLICY_FILE\fR
JSON file with the IAM policy


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-keyring\fR=\fIKEYRING\fR
The containing keyring.

.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
The location of the requested resource.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

The following command will read am IAM policy defined in a JSON file
\'policy.json' and set it for the key \f5frodo\fR with the keyring
\f5fellowship\fR and location \f5global\fR:

.RS 2m
$ gcloud kms keys set\-iam\-policy frodo policy.json \e
    \-\-keyring fellowship \-\-location global
.RE
