
.TH "GCLOUD_FIREBASE_TEST_ANDROID_LOCALES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud firebase test android locales describe \- describe an Android locale



.SH "SYNOPSIS"
.HP
\f5gcloud firebase test android locales describe\fR \fILOCALE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Describe an Android locale.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fILOCALE\fR
The locale to describe, found using $ gcloud firebase test android locales list.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
