
.TH "GCLOUD_DEPLOYMENT\-MANAGER_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud deployment\-manager operations describe \- provide information about an operation



.SH "SYNOPSIS"
.HP
\f5gcloud deployment\-manager operations describe\fR \fIOPERATION_NAME\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command prints out all available details about an operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION_NAME\fR
Operation name.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To display information about an operation, run:

.RS 2m
$ gcloud deployment\-manager operations describe operation\-name
.RE
