
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_ADD\-IAM\-POLICY\-BINDING" 1



.SH "NAME"
.HP
gcloud iam service\-accounts add\-iam\-policy\-binding \- add IAM policy binding for a service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts add\-iam\-policy\-binding\fR \fIIAM_ACCOUNT\fR \fB\-\-member\fR=\fIMEMBER\fR \fB\-\-role\fR=\fIROLE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command adds a policy binding to the IAM policy of a service account, given
an IAM_ACCOUNT and the binding.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIAM_ACCOUNT\fR
The service account whose policy to add bindings to.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-member\fR=\fIMEMBER\fR
The member to add to the binding. Should be of the form \f5user:user_email\fR
(e.g. \f5user:test\-user@gmail.com.\fR)

.TP 2m
\fB\-\-role\fR=\fIROLE\fR
Define the role of the member.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

The following command will add an IAM policy binding for the role of
\'roles/editor' for the user 'test\-user@gmail.com' on a service account with
identifier 'my\-iam\-account@somedomain.com'

.RS 2m
$ gcloud iam service\-accounts add\-iam\-policy\-binding \e
    my\-iam\-account@somedomain.com \e
    \-\-member='user:test\-user@gmail.com' \-\-role='roles/editor'
.RE

See https://cloud.google.com/iam/docs/managing\-policies for details of policy
role and member types.
