
.TH "GCLOUD_CONTAINER_IMAGES_DELETE" 1



.SH "NAME"
.HP
gcloud container images delete \- delete existing images



.SH "SYNOPSIS"
.HP
\f5gcloud container images delete\fR \fIIMAGE_NAMES\fR [\fIIMAGE_NAMES\fR\ ...] [\fB\-\-force\-delete\-tags\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

The container images delete command deletes the specified image from the
registry. All associated tags are also deleted.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIMAGE_NAMES\fR [\fIIMAGE_NAMES\fR ...]
The IMAGE_NAME or IMAGE_NAMES to delete Format For Digest:
*.gcr.io/repository@sha256:<digest> Format For Tag: *.gcr.io/repository:<tag>


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-force\-delete\-tags\fR
If there are tags pointing to an image to be deleted then they must all be
specified explicitly, or this flag must be specified, for the command to
succeed.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

Deletes the image (and tags) from the input IMAGE_NAME:

.RS 2m
$ gcloud container images delete <IMAGE_NAME>
.RE
