
.TH "GCLOUD_SPANNER_INSTANCES_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud spanner instances set\-iam\-policy \- set the IAM policy for a Cloud Spanner instance



.SH "SYNOPSIS"
.HP
\f5gcloud spanner instances set\-iam\-policy\fR \fIINSTANCE\fR \fIPOLICY_FILE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Set the IAM policy for a Cloud Spanner instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR
Cloud Spanner instance ID.

.TP 2m
\fIPOLICY_FILE\fR
Name of JSON or YAML file with the IAM policy.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
