
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_CREATE" 1



.SH "NAME"
.HP
gcloud iam service\-accounts create \- create a service account for a project



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts create\fR \fINAME\fR [\fB\-\-display\-name\fR=\fIDISPLAY_NAME\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command creates a service account with the provided name. For subsequent
commands regarding service accounts, this service account should be referred to
by the email account in the response.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The internal name of the new service account. Used to generate an IAM_ACCOUNT
(an IAM internal email address used as an identifier of service account), which
must be passed to subsequent commands.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-display\-name\fR=\fIDISPLAY_NAME\fR
A textual name to display for the account.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To create a service account for your project, run:

.RS 2m
$ gcloud iam service\-accounts create some\-account\-name \e
    \-\-display\-name "My Service Account"
.RE

To work with this service account in subsequent IAM commands, use the email
resulting from this call as the IAM_ACCOUNT argument.
