
.TH "GCLOUD_COMPUTE_XPN_GET\-HOST\-PROJECT" 1



.SH "NAME"
.HP
gcloud compute xpn get\-host\-project \- get the XPN host project that the given project is linked to



.SH "SYNOPSIS"
.HP
\f5gcloud compute xpn get\-host\-project\fR \fIPROJECT_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Get the shared VPC network (XPN) host project of this project, whose networks
can be accessed from this one via XPN.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIPROJECT_ID\fR
ID for the project to get the host project for


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

If the project \f5xpn\-user\fR can use the project \f5xpn\-host\fR via XPN,

.RS 2m
$ gcloud compute xpn get\-host\-project xpn\-user
.RE

will show the \f5xpn\-host\fR project.
