
.TH "GCLOUD_FEEDBACK" 1



.SH "NAME"
.HP
gcloud feedback \- provide feedback to the Google Cloud SDK team



.SH "SYNOPSIS"
.HP
\f5gcloud feedback\fR [\fB\-\-log\-file\fR=\fILOG_FILE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

The Google Cloud SDK team offers support through a number of channels:

.RS 2m
.IP "\(bu" 2m
Google Cloud SDK Issue Tracker
.IP "\(bu" 2m
Stack Overflow "#gcloud" tag
.IP "\(bu" 2m
google\-cloud\-dev Google group
.RE
.sp

This command lists the available channels and facilitates getting help through
one of them by opening a web browser to the relevant page, possibly with
information relevant to the current install and configuration pre\-populated in
form fields on that page.



.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-log\-file\fR=\fILOG_FILE\fR
Path to the log file from a prior gcloud run.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
