
.TH "GCLOUD_APP_VERSIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud app versions describe \- display all data about an existing version



.SH "SYNOPSIS"
.HP
\f5gcloud app versions describe\fR \fIVERSION\fR \fB\-\-service\fR=\fISERVICE\fR, \fB\-s\fR \fISERVICE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Display all data about an existing version.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIVERSION\fR
The ID of the version to show.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-service\fR=\fISERVICE\fR, \fB\-s\fR \fISERVICE\fR
The service corresponding to the version to show.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
