
.TH "GCLOUD_ML\-ENGINE_OPERATIONS_DELETE" 1



.SH "NAME"
.HP
gcloud ml\-engine operations delete \- delete a Cloud ML Engine operation



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine operations delete\fR \fIOPERATION\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete a Cloud ML Engine operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR
Name of the operation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
