
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_UPDATE" 1



.SH "NAME"
.HP
gcloud iam service\-accounts update \- update the metadata of an IAM service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts update\fR \fIIAM_ACCOUNT\fR [\fB\-\-display\-name\fR=\fIDISPLAY_NAME\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Update the metadata of an IAM service account.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIAM_ACCOUNT\fR
The IAM service account to update.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-display\-name\fR=\fIDISPLAY_NAME\fR
The new textual name to display for the account.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
