
.TH "GCLOUD_ML\-ENGINE_JOBS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud ml\-engine jobs describe \- describe a Cloud ML Engine job



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine jobs describe\fR \fIJOB\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Describe a Cloud ML Engine job.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB\fR
Name of the job.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
