
.TH "GCLOUD_COMPUTE_BACKEND\-BUCKETS_DELETE" 1



.SH "NAME"
.HP
gcloud compute backend\-buckets delete \- delete backend buckets



.SH "SYNOPSIS"
.HP
\f5gcloud compute backend\-buckets delete\fR \fIBACKEND_BUCKET_NAME\fR [\fIBACKEND_BUCKET_NAME\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute backend\-buckets delete\fR deletes one or more backend
buckets.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIBACKEND_BUCKET_NAME\fR [\fIBACKEND_BUCKET_NAME\fR ...]
The names of the backend buckets to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
