
.TH "GCLOUD_DATAFLOW" 1



.SH "NAME"
.HP
gcloud dataflow \- manage Google Cloud Dataflow jobs



.SH "SYNOPSIS"
.HP
\f5gcloud dataflow\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

The gcloud dataflow command group lets you manage Google Cloud Dataflow jobs.

Cloud Dataflow is a unified programming model and a managed service for
developing and executing a wide range of data processing patterns including ETL,
batch computation, and continuous computation.

More information on Cloud Dataflow can be found here:
https://cloud.google.com/dataflow and detailed documentation can be found here:
https://cloud.google.com/dataflow/docs/



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBjobs\fR
A group of subcommands for working with Dataflow jobs.
.RE
.sp
