
.TH "GCLOUD_PROJECTS_UNDELETE" 1



.SH "NAME"
.HP
gcloud projects undelete \- undelete a project



.SH "SYNOPSIS"
.HP
\f5gcloud projects undelete\fR \fIPROJECT_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Undeletes the project with the given project ID.

This command can fail for the following reasons:
.RS 2m
.IP "\(bu" 2m
There is no project with the given ID.
.IP "\(bu" 2m
The active account does not have Owner or Editor permissions for the given
project.
.RE
.sp



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIPROJECT_ID\fR
ID for the project you want to undelete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

The following command undeletes the project with the ID
\f5example\-foo\-bar\-1\fR:

.RS 2m
$ gcloud projects undelete example\-foo\-bar\-1
.RE
