
.TH "GCLOUD_FIREBASE_TEST_ANDROID_LOCALES" 1



.SH "NAME"
.HP
gcloud firebase test android locales \- explore Android locales available for testing



.SH "SYNOPSIS"
.HP
\f5gcloud firebase test android locales\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Explore Android locales available for testing.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Describe an Android locale.

.TP 2m
\fBlist\fR
List all Android locales available for testing internationalized apps.


.RE
.sp

.SH "EXAMPLES"

To list all available Android locales which can be used for testing
international applications, run:

.RS 2m
$ gcloud firebase test android locales list
.RE

To view information about a specific locale, run:

.RS 2m
$ gcloud firebase test android locales describe LOCALE
.RE
