
.TH "GCLOUD_KMS_KEYRINGS_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud kms keyrings set\-iam\-policy \- set the IAM policy for a keyring



.SH "SYNOPSIS"
.HP
\f5gcloud kms keyrings set\-iam\-policy\fR \fIKEYRING\fR \fIPOLICY_FILE\fR [\fB\-\-location\fR=\fILOCATION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Sets the IAM policy for the given keyring as defined in a JSON file.

See https://cloud.google.com/iam/docs/managing\-policies for details of the
policy file format and contents.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIKEYRING\fR
Name of the keyring whose IAM policy to update.

.TP 2m
\fIPOLICY_FILE\fR
JSON file with the IAM policy


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-location\fR=\fILOCATION\fR
The location of the requested resource.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

The following command will read am IAM policy defined in a JSON file
\'policy.json' and set it for the keyring \f5fellowship\fR with location
\f5global\fR:

.RS 2m
$ gcloud kms keyrings set\-iam\-policy fellowship policy.json \e
    \-\-location global
.RE
