
.TH "GCLOUD_SPANNER_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud spanner operations describe \- describe a Cloud Spanner operation



.SH "SYNOPSIS"
.HP
\f5gcloud spanner operations describe\fR \fIOPERATION\-ID\fR \fB\-\-instance\fR=\fIINSTANCE\fR [\fB\-\-database\fR=\fIDATABASE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Describe a Cloud Spanner operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\-ID\fR
ID of the operation


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR
The ID of the instance the operation is executing on.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-database\fR=\fIDATABASE\fR
For a database operation, the name of the database the operation is executing
on.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
