
.TH "GCLOUD_ML\-ENGINE_MODELS_CREATE" 1



.SH "NAME"
.HP
gcloud ml\-engine models create \- create a new Cloud ML Engine model



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine models create\fR \fIMODEL\fR [\fB\-\-enable\-logging\fR] [\fB\-\-regions\fR=\fIREGION\fR,[\fIREGION\fR,...]] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Create a new Cloud ML Engine model.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIMODEL\fR
Name of the model.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-enable\-logging\fR
If set, enables StackDriver Logging for online prediction.

.TP 2m
\fB\-\-regions\fR=\fIREGION\fR,[\fIREGION\fR,...]
The Google Cloud region where the model will be deployed (currently only a
single region is supported).

Will soon be required, but defaults to 'us\-central1' for now.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
