
.TH "GCLOUD_DNS_RECORD\-SETS_EXPORT" 1



.SH "NAME"
.HP
gcloud dns record\-sets export \- export your record\-sets into a file



.SH "SYNOPSIS"
.HP
\f5gcloud dns record\-sets export\fR \fIRECORDS_FILE\fR \fB\-\-zone\fR=\fIZONE\fR, \fB\-z\fR \fIZONE\fR [\fB\-\-zone\-file\-format\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command exports the record\-sets contained within the specified
managed\-zone into a file.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIRECORDS_FILE\fR
File to which record\-sets should be exported.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-zone\fR=\fIZONE\fR, \fB\-z\fR \fIZONE\fR
Name of the managed\-zone whose record\-sets you want to manage.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-zone\-file\-format\fR
Indicates that records\-file should be in the zone file format.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To export record\-sets into a yaml file, run:

.RS 2m
$ gcloud dns record\-sets export YAML_RECORDS_FILE \-\-zone MANAGED_ZONE
.RE

To import record\-sets into a zone file, run:

.RS 2m
$ gcloud dns record\-sets export ZONE_FILE \-\-zone\-file\-format \e
    \-\-zone MANAGED_ZONE
.RE
