
.TH "GCLOUD_COMPUTE_DISK\-TYPES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute disk\-types describe \- describe a Google Compute Engine disk type



.SH "SYNOPSIS"
.HP
\f5gcloud compute disk\-types describe\fR \fIDISK_TYPE\fR [\fB\-\-zone\fR=\fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute disk\-types describe\fR displays all data associated with a
Google Compute Engine disk type.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIDISK_TYPE\fR
The name of the disk type to describe.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-zone\fR=\fIZONE\fR
The zone of the disk type to describe. Overrides the default \fBcompute/zone\fR
property value for this command invocation.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
