
.TH "GCLOUD_SERVICE\-MANAGEMENT_CONFIGS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud service\-management configs describe \- describes the configuration for a given version of a service



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management configs describe\fR \fICONFIG_ID\fR [\fB\-\-service\fR=\fISERVICE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command prints out the configuration for the given version of a given
service. You specify the name of the service and the ID of the configuration,
and the command will print out the specified config.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fICONFIG_ID\fR
The configuration ID to retrieve.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-service\fR=\fISERVICE\fR
The service from which to retrieve the configuration.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To print the configuration with ID \f5\fI2017\-01\-01R0\fR\fR for the service
called \f5\fImy\-service\fR\fR, run:

.RS 2m
$ gcloud service\-management configs describe \-\-service my\-service \e
    2017\-01\-01R0
.RE
