
.TH "GCLOUD_FIREBASE_TEST_ANDROID_VERSIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud firebase test android versions describe \- describe an Android OS version



.SH "SYNOPSIS"
.HP
\f5gcloud firebase test android versions describe\fR \fIVERSION_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Describe an Android OS version.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIVERSION_ID\fR
The version ID to describe, found using $ gcloud firebase test android versions
list.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
