
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_DELETE" 1



.SH "NAME"
.HP
gcloud iam service\-accounts delete \- delete a service account from a project



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts delete\fR \fIIAM_ACCOUNT\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete a service account from a project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIAM_ACCOUNT\fR
The service account to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To delete an service account from your project, run:

.RS 2m
$ gcloud iam service\-accounts delete my\-iam\-account@somedomain.com
.RE
