
.TH "GCLOUD_SERVICE\-MANAGEMENT_DISABLE" 1



.SH "NAME"
.HP
gcloud service\-management disable \- disables a service for consumption for a project



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management disable\fR \fISERVICE\fR [\fB\-\-async\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command disables a previously\-enabled service for consumption.

To see a list of the enabled services for a project, run:

.RS 2m
$ gcloud service\-management list \-\-enabled
.RE

More information on listing services can be found at:
https://cloud.google.com/service\-management/list\-services and on disabling a
service at:
https://cloud.google.com/service\-management/enable\-disable#disabling_services



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISERVICE\fR
The name of the service to disable.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress, without waiting for the
operation to complete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To disable a service called \f5my\-consumed\-service\fR for the active project,
run:

.RS 2m
$ gcloud service\-management disable my\-consumed\-service
.RE

To run the same command asynchronously (non\-blocking), run:

.RS 2m
$ gcloud service\-management disable my\-consumed\-service \-\-async
.RE
