
.TH "GCLOUD_COMPUTE_IMAGES" 1



.SH "NAME"
.HP
gcloud compute images \- list, create, and delete Google Compute Engine images



.SH "SYNOPSIS"
.HP
\f5gcloud compute images\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

List, create, and delete Google Compute Engine images.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-labels\fR
Add labels to Google Compute Engine images.

.TP 2m
\fBcreate\fR
Create Google Compute Engine images.

.TP 2m
\fBdelete\fR
Delete Google Compute Engine images.

.TP 2m
\fBdeprecate\fR
Manage deprecation status of Google Compute Engine images.

.TP 2m
\fBdescribe\fR
Describe a Google Compute Engine image.

.TP 2m
\fBdescribe\-from\-family\fR
Describe the latest image from an image family.

.TP 2m
\fBlist\fR
List Google Compute Engine images.

.TP 2m
\fBremove\-labels\fR
Remove labels from Google Compute Engine images.

.TP 2m
\fBupdate\fR
Update a Google Compute Engine image.
.RE
.sp
