
.TH "GCLOUD_CONFIG_CONFIGURATIONS_LIST" 1



.SH "NAME"
.HP
gcloud config configurations list \- lists existing named configurations



.SH "SYNOPSIS"
.HP
\f5gcloud config configurations list\fR [\fB\-\-filter\fR=\fIEXPRESSION\fR] [\fB\-\-limit\fR=\fILIMIT\fR] [\fB\-\-sort\-by\fR=[\fIFIELD\fR,...]] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Lists existing named configurations.

Run \f5$ gcloud topic configurations\fR for an overview of named configurations.



.SH "LIST COMMAND FLAGS"

.RS 2m
.TP 2m
\fB\-\-filter\fR=\fIEXPRESSION\fR
Apply a Boolean filter \fIEXPRESSION\fR to each resource item to be listed. If
the expression evaluates True then that item is listed. For more details and
examples of filter expressions run $ gcloud topic filters. This flag interacts
with other flags that are applied in this order: \fB\-\-flatten\fR,
\fB\-\-sort\-by\fR, \fB\-\-filter\fR, \fB\-\-limit\fR.

.TP 2m
\fB\-\-limit\fR=\fILIMIT\fR
The maximum number of resources to list. The default is \fBunlimited\fR. This
flag interacts with other flags that are applied in this order:
\fB\-\-flatten\fR, \fB\-\-sort\-by\fR, \fB\-\-filter\fR, \fB\-\-limit\fR.

.TP 2m
\fB\-\-sort\-by\fR=[\fIFIELD\fR,...]
A comma\-separated list of resource field key names to sort by. The default
order is ascending. Prefix a field with ``~'' for descending order on that
field. This flag interacts with other flags that are applied in this order:
\fB\-\-flatten\fR, \fB\-\-sort\-by\fR, \fB\-\-filter\fR, \fB\-\-limit\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To list all available configurations, run:

.RS 2m
$ gcloud config configurations list
.RE
