
.TH "GCLOUD_CONTAINER_IMAGES" 1



.SH "NAME"
.HP
gcloud container images \- list and manipulate Google Container Registry images



.SH "SYNOPSIS"
.HP
\f5gcloud container images\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

List and manipulate Google Container Registry images.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-tag\fR
Adds tags to existing image.

.TP 2m
\fBdelete\fR
Delete existing images.

.TP 2m
\fBdescribe\fR
Lists container analysis data for a given image.

.TP 2m
\fBlist\fR
List existing images.

.TP 2m
\fBlist\-tags\fR
List tags and digests for the specified image.

.TP 2m
\fBuntag\fR
Remove existing image tags.
.RE
.sp
