
.TH "GCLOUD_DEBUG_TARGETS" 1



.SH "NAME"
.HP
gcloud debug targets \- commands for interacting with Cloud Debugger debug targets



.SH "SYNOPSIS"
.HP
\f5gcloud debug targets\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Commands to interact with debug targets. A debug target can be an App Engine
module version or any other entity enabled for use with the cloud debugger.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlist\fR
List debug targets.


.RE
.sp

.SH "EXAMPLES"

To view all available debug targets, run:

.RS 2m
$ gcloud debug targets list
.RE
