
.TH "GCLOUD_COMPUTE_DISKS_DELETE" 1



.SH "NAME"
.HP
gcloud compute disks delete \- delete Google Compute Engine persistent disks



.SH "SYNOPSIS"
.HP
\f5gcloud compute disks delete\fR \fIDISK_NAME\fR [\fIDISK_NAME\fR\ ...] [\fB\-\-zone\fR=\fIZONE\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute disks delete\fR deletes one or more Google Compute Engine
persistent disks. Disks can be deleted only if they are not being used by any
virtual machine instances.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIDISK_NAME\fR [\fIDISK_NAME\fR ...]
The names of the disks to delete.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-zone\fR=\fIZONE\fR
The zone of the disks to delete. If not specified, you may be prompted to select
a zone.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/zone\fR\fR property:

.RS 2m
$ gcloud config set compute/zone ZONE
.RE

A list of zones can be fetched by running:

.RS 2m
$ gcloud compute zones list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/zone
.RE

Alternatively, the zone can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_ZONE\fR\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
