
.TH "GCLOUD_DEPLOYMENT\-MANAGER" 1



.SH "NAME"
.HP
gcloud deployment\-manager \- manage deployments of cloud resources



.SH "SYNOPSIS"
.HP
\f5gcloud deployment\-manager\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

The gcloud deployment\-manager command group lets you manage the deployment of
Google Cloud Platform resources using Google Cloud Deployment Manager.

Google Cloud Deployment Manager allows you to specify all the resources needed
for your application in a declarative format using YAML. You can also use Python
or Jinja2 templates to parameterize the configuration and allow reuse of common
deployment paradigms such as a load balanced, auto\-scaled instance group.

More information on Cloud Deployment Manager can be found here:
https://cloud.google.com/deployment\-manager and detailed documentation can be
found here: https://cloud.google.com/deployment\-manager/docs/



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdeployments\fR
Commands for Deployment Manager deployments.

.TP 2m
\fBmanifests\fR
Commands for Deployment Manager manifests.

.TP 2m
\fBoperations\fR
Commands for Deployment Manager operations.

.TP 2m
\fBresources\fR
Commands for Deployment Manager resources.

.TP 2m
\fBtypes\fR
Commands for Deployment Manager types.
.RE
.sp
