
.TH "GCLOUD_DNS_PROJECT\-INFO_DESCRIBE" 1



.SH "NAME"
.HP
gcloud dns project\-info describe \- view Cloud DNS related information for a project



.SH "SYNOPSIS"
.HP
\f5gcloud dns project\-info describe\fR \fIPROJECT_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command displays Cloud DNS related information for your project including
quotas for various resources and operations.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIPROJECT_ID\fR
The identifier for the project you want DNS related info for.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To display Cloud DNS related information for your project, run:

.RS 2m
$ gcloud dns project\-info describe my_project_id
.RE
