
.TH "GCLOUD_CONFIG_CONFIGURATIONS" 1



.SH "NAME"
.HP
gcloud config configurations \- manage the set of gcloud named configurations



.SH "SYNOPSIS"
.HP
\f5gcloud config configurations\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage the set of gcloud named configurations.

See \f5gcloud topic configurations\fR for an overview of named configurations.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBactivate\fR
Activates an existing named configuration.

.TP 2m
\fBcreate\fR
Creates a new named configuration.

.TP 2m
\fBdelete\fR
Deletes a named configuration.

.TP 2m
\fBdescribe\fR
Describes a named configuration by listing its properties.

.TP 2m
\fBlist\fR
Lists existing named configurations.
.RE
.sp
