
.TH "GCLOUD_SOURCE_REPOS" 1



.SH "NAME"
.HP
gcloud source repos \- manage cloud source repositories



.SH "SYNOPSIS"
.HP
\f5gcloud source repos\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage cloud source repositories.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBclone\fR
Clone project git repository in the current directory.

.TP 2m
\fBcreate\fR
Create a cloud source repository.

.TP 2m
\fBdelete\fR
Delete a cloud source repository.

.TP 2m
\fBdescribe\fR
Describe a cloud source repository.

.TP 2m
\fBget\-iam\-policy\fR
Get the IAM policy for the named cloud source repository.

.TP 2m
\fBlist\fR
List the repositories the currently active project.

.TP 2m
\fBset\-iam\-policy\fR
Set the IAM policy for the named repository.
.RE
.sp
