
.TH "GCLOUD_COMPUTE_SSL\-CERTIFICATES_DELETE" 1



.SH "NAME"
.HP
gcloud compute ssl\-certificates delete \- delete Google Compute Engine SSL certificates



.SH "SYNOPSIS"
.HP
\f5gcloud compute ssl\-certificates delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute ssl\-certificates delete\fR deletes one or more Google Compute
Engine SSL certificates. SSL certificates can only be deleted when no other
resources (e.g., target HTTPS proxies) refer to them.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The names of the SSL certificates to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
