
.TH "GCLOUD_COMPUTE_NETWORKS_SWITCH\-MODE" 1



.SH "NAME"
.HP
gcloud compute networks switch\-mode \- switch the mode of a Google Compute Engine network



.SH "SYNOPSIS"
.HP
\f5gcloud compute networks switch\-mode\fR \fINAME\fR \fB\-\-mode\fR=\fIMODE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute networks switch\-mode\fR is used to change the mode of a
network. Currently, only changing from auto to custom mode is supported.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the network for which to switch mode.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-mode\fR=\fIMODE\fR
The target mode of the network. Only support "custom" now.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To switch \f5\fINETWORK\fR\fR to custom subnet mode, run:

.RS 2m
$ gcloud compute networks switch\-mode NETWORK \-\-mode custom
.RE
