
.TH "GCLOUD_SPANNER_DATABASES_CREATE" 1



.SH "NAME"
.HP
gcloud spanner databases create \- create a Cloud Spanner database



.SH "SYNOPSIS"
.HP
\f5gcloud spanner databases create\fR \fIDATABASE\fR \fB\-\-instance\fR=\fIINSTANCE\fR [\fB\-\-async\fR] [\fB\-\-ddl\fR=\fIDDL\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Create a Cloud Spanner database.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIDATABASE\fR
Cloud Spanner database ID.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR
Cloud Spanner instance ID.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress, without waiting for the
operation to complete.

.TP 2m
\fB\-\-ddl\fR=\fIDDL\fR
Semi\-colon separated DDL (data definition language) statements to run inside
the newly created database. If there is an error in any statement, the database
is not created. Full DDL specification is at
https://cloud.google.com/spanner/docs/data\-definition\-language


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
