
.TH "GCLOUD_COMPUTE_TARGET\-TCP\-PROXIES_DELETE" 1



.SH "NAME"
.HP
gcloud compute target\-tcp\-proxies delete \- delete target TCP proxies



.SH "SYNOPSIS"
.HP
\f5gcloud compute target\-tcp\-proxies delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute target\-tcp\-proxies delete\fR deletes one or more target TCP
proxies.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The names of the target TCP proxies to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
