
.TH "GCLOUD_ORGANIZATIONS_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud organizations set\-iam\-policy \- set IAM policy for an organization



.SH "SYNOPSIS"
.HP
\f5gcloud organizations set\-iam\-policy\fR \fIORGANIZATION_ID\fR \fIPOLICY_FILE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Given an organization ID and a file encoded in JSON or YAML that contains the
IAM policy, this command will set the IAM policy for that organization.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIORGANIZATION_ID\fR
ID for the organization whose IAM policy you want to set.

.TP 2m
\fIPOLICY_FILE\fR
JSON or YAML file containing the IAM policy.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

The following command reads an IAM policy defined in a JSON file
\f5policy.json\fR and sets it for an organization with the ID \f5123456789\fR:

.RS 2m
$ gcloud organizations set\-iam\-policy 123456789 policy.json
.RE
