
.TH "GCLOUD_COMPUTE_TARGET\-POOLS_REMOVE\-HEALTH\-CHECKS" 1



.SH "NAME"
.HP
gcloud compute target\-pools remove\-health\-checks \- remove an HTTP health check from a target pool



.SH "SYNOPSIS"
.HP
\f5gcloud compute target\-pools remove\-health\-checks\fR \fINAME\fR \fB\-\-http\-health\-check\fR=\fIHTTP_HEALTH_CHECK\fR [\fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute target\-pools remove\-health\-checks\fR is used to remove an
HTTP health check from a target pool. Health checks are used to determine the
health status of instances in the target pool. For more information on health
checks and load balancing, see
https://cloud.google.com/compute/docs/load\-balancing\-and\-autoscaling/



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the target pool from which to remove the health check.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-http\-health\-check\fR=\fIHTTP_HEALTH_CHECK\fR
Specifies an HTTP health check object to remove from the target pool.


.RE
.sp

.SH "OPTIONAL FLAGS"

.RS 2m
.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region of the target pool to remove health checks from. If not specified,
you will be prompted to select a region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
