
.TH "GCLOUD_CONFIG_CONFIGURATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud config configurations describe \- describes a named configuration by listing its properties



.SH "SYNOPSIS"
.HP
\f5gcloud config configurations describe\fR \fICONFIGURATION_NAME\fR [\fB\-\-all\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Describes a named configuration by listing its properties.

See \f5gcloud topic configurations\fR for an overview of named configurations.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fICONFIGURATION_NAME\fR
Name of the configuration to describe


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-all\fR
Include unset properties in output.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To describe existing named configuration, run:

.RS 2m
$ gcloud config configurations describe my_config
.RE

This is similar to:

.RS 2m
$ gcloud config configurations activate my_config
.RE

.RS 2m
$ gcloud config list
.RE
