
.TH "GCLOUD_ML\-ENGINE_JOBS_STREAM\-LOGS" 1



.SH "NAME"
.HP
gcloud ml\-engine jobs stream\-logs \- show logs from a running Cloud ML Engine job



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine jobs stream\-logs\fR \fIJOB\fR [\fB\-\-allow\-multiline\-logs\fR] [\fB\-\-polling\-interval\fR=\fIPOLLING_INTERVAL\fR;\ default="60"] [\fB\-\-task\-name\fR=\fITASK_NAME\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Show logs from a running Cloud ML Engine job.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB\fR
Name of the job.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-allow\-multiline\-logs\fR
Output multiline log messages as single records.

.TP 2m
\fB\-\-polling\-interval\fR=\fIPOLLING_INTERVAL\fR; default="60"
Number of seconds to wait between efforts to fetch the latest log messages.
Overrides the default \fBml_engine/polling_interval\fR property value for this
command invocation.

.TP 2m
\fB\-\-task\-name\fR=\fITASK_NAME\fR
If set, display only the logs for this particular task.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
