
.TH "GCLOUD_ML" 1



.SH "NAME"
.HP
gcloud ml \- use Google Cloud machine learning capabilities



.SH "SYNOPSIS"
.HP
\f5gcloud ml\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Use Google Cloud machine learning capabilities.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlanguage\fR
Use the Google Cloud Natural Language API to analyze text.
.RE
.sp
