
.TH "GCLOUD_COMPUTE_SNAPSHOTS_DELETE" 1



.SH "NAME"
.HP
gcloud compute snapshots delete \- delete Google Compute Engine snapshots



.SH "SYNOPSIS"
.HP
\f5gcloud compute snapshots delete\fR \fISNAPSHOT_NAME\fR [\fISNAPSHOT_NAME\fR\ ...] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute snapshots delete\fR deletes one or more Google Compute Engine
snapshots.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISNAPSHOT_NAME\fR [\fISNAPSHOT_NAME\fR ...]
The names of the snapshots to delete.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
