
.TH "GCLOUD_SERVICE\-MANAGEMENT_CHECK\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud service\-management check\-iam\-policy \- returns information about a member's permissions on a service



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management check\-iam\-policy\fR \fISERVICE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command lists the permissions that the current authenticated gcloud user
has for a service. For example, if the authenticated user is able to delete the
service, \f5servicemanagement.services.delete\fR will be among the returned
permissions.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISERVICE\fR
The name of the service for which to check the IAM policy.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To check the permissions for the currently authenticated gcloud, run:

.RS 2m
$ gcloud service\-management check\-iam\-policy my_produced_service_name
.RE
