
.TH "GCLOUD_COMPUTE_MACHINE\-TYPES" 1



.SH "NAME"
.HP
gcloud compute machine\-types \- read Google Compute Engine virtual machine types



.SH "SYNOPSIS"
.HP
\f5gcloud compute machine\-types\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Read Google Compute Engine virtual machine types.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Describe a Google Compute Engine machine type.

.TP 2m
\fBlist\fR
List Google Compute Engine machine types.
.RE
.sp
