
.TH "GCLOUD_DATAFLOW_JOBS" 1



.SH "NAME"
.HP
gcloud dataflow jobs \- a group of subcommands for working with Dataflow jobs



.SH "SYNOPSIS"
.HP
\f5gcloud dataflow jobs\fR \fICOMMAND\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

A group of subcommands for working with Dataflow jobs.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcancel\fR
Cancels all jobs that match the command line arguments.

.TP 2m
\fBdescribe\fR
Outputs the Job object resulting from the Get API.

.TP 2m
\fBdrain\fR
Drains all jobs that match the command line arguments.

.TP 2m
\fBlist\fR
Lists all jobs in a particular project.

.TP 2m
\fBrun\fR
Runs a job from the specified path.

.TP 2m
\fBshow\fR
Shows a short description of the given job.
.RE
.sp
