
.TH "GCLOUD_ML\-ENGINE_VERSIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud ml\-engine versions describe \- describe an existing Cloud ML Engine version



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine versions describe\fR \fIVERSION\fR \fB\-\-model\fR=\fIMODEL\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Describe an existing Cloud ML Engine version.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIVERSION\fR
Name of the model version.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-model\fR=\fIMODEL\fR
Name of the model.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
