
.TH "GCLOUD_COMPUTE_FORWARDING\-RULES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute forwarding\-rules describe \- display detailed information about a forwarding rule



.SH "SYNOPSIS"
.HP
\f5gcloud compute forwarding\-rules describe\fR \fINAME\fR [\fB\-\-global\fR\ |\ \fB\-\-region\fR=\fIREGION\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute forwarding\-rules describe\fR displays all data associated
with a forwarding rule in a project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the forwarding rule to describe.


.RE
.sp

.SH "FLAGS"

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-global\fR
If provided, it is assumed the forwarding rule is global.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region of the forwarding rule to describe. If not specified, you will be
prompted to select a region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To get details about a global forwarding rule, run:

.RS 2m
$ gcloud compute forwarding\-rules describe FORWARDING\-RULE \-\-global
.RE

To get details about a regional forwarding rule, run:

.RS 2m
$ gcloud compute forwarding\-rules describe FORWARDING\-RULE \e
    \-\-region us\-central1
.RE
